from __future__ import annotations

import asyncio
import importlib.util
import subprocess
import sys
from collections.abc import Awaitable
from datetime import UTC, datetime, timedelta
from pathlib import Path

from crickey import id_tables
from crickey.fetcher import Fetcher, MemoryPageSource
from crickey.ids import (
    FORM_URL,
    INVOLVE_URL,
    LookupStatus,
    StatsguruIdResolver,
    lookup_continent,
    lookup_team,
    lookup_trophy,
    resolve_name,
)
from crickey.settings import Settings

_GEN_IDS_SPEC = importlib.util.spec_from_file_location(
    "gen_ids_for_tests", Path(__file__).parents[1] / "scripts" / "gen_ids.py"
)
assert _GEN_IDS_SPEC is not None and _GEN_IDS_SPEC.loader is not None
_GEN_IDS_MODULE = importlib.util.module_from_spec(_GEN_IDS_SPEC)
sys.modules[_GEN_IDS_SPEC.name] = _GEN_IDS_MODULE
_GEN_IDS_SPEC.loader.exec_module(_GEN_IDS_MODULE)
CLASS_IDS = _GEN_IDS_MODULE.CLASS_IDS
module_text_from_html_by_class = _GEN_IDS_MODULE.module_text_from_html_by_class


class FakeClock:
    def __init__(self) -> None:
        self.monotonic_time = 0.0
        self.wall_time = datetime(2026, 10, 4, tzinfo=UTC)
        self.sleeps: list[float] = []

    def monotonic(self) -> float:
        return self.monotonic_time

    def now(self) -> datetime:
        return self.wall_time + timedelta(seconds=self.monotonic_time)

    async def sleep(self, seconds: float) -> None:
        self.sleeps.append(seconds)
        self.monotonic_time += seconds
        await asyncio.sleep(0)


def run(coro: Awaitable[object]) -> object:
    return asyncio.run(coro)


def settings() -> Settings:
    return Settings(min_interval=timedelta(seconds=2), max_retries=0)


def form_html(
    *,
    spanmin0: str = "01 Jan 2000",
    team_label: str = "Alpha XI",
    ground_value: int = 701,
    ground_label: str = "AAA: Alpha Ground",
    series_label: str = "Alpha Cup, 2026",
    include_new_ground: bool = False,
    include_new_series: bool = False,
    extra_ground_options: str = "",
    extra_series_options: str = "",
    involve_field: str | None = None,
    opposition_label: str | None = None,
) -> str:
    new_ground = '<option value="702">BBB: New Ground</option>' if include_new_ground else ""
    new_series = '<option value="802">New Series, 2026</option>' if include_new_series else ""
    series_options = (
        f'<option value="801">{series_label}</option>{new_series}{extra_series_options}'
    )
    opposition_label = team_label if opposition_label is None else opposition_label
    involve = ""
    if involve_field is not None:
        involve = (
            f'<input type="checkbox" name="{involve_field}" value="56880" checked>'
            ' found using "babar azam": Babar Azam (PAK)'
        )
    return f"""
    <html><body><form name="gurumenu">
    <input type="hidden" name="spanmin0" value="{spanmin0}">
    <select name="team">
      <option value="">all teams</option>
      <option value="7">{team_label}</option>
      <option value="8">Beta XI</option>
    </select>
    <select name="opposition">
      <option value="">all teams</option>
      <option value="7">{opposition_label}</option>
      <option value="8">Beta XI</option>
    </select>
    <select name="host">
      <option value="">all countries</option><option value="1">Hostland</option>
    </select>
    <select name="continent">
      <option value="">all continents</option><option value="2">Asia</option>
    </select>
    <select name="trophy">
      <option value="">all tournaments</option>
      <option value="12">World Cup</option>
      <option value="117">Indian Premier League</option>
    </select>
    <select name="ground">
      <option value="">all grounds</option>
      <option value="{ground_value}">{ground_label}</option>{new_ground}{extra_ground_options}
    </select>
    <select name="series">
      <option value="">all series</option>{series_options}
    </select>
    {involve}
    </form></body></html>
    """


def test_generator_builds_exact_tables_from_synthetic_forms() -> None:
    html_by_class = {
        class_id: form_html(spanmin0=f"0{index} Jan 2000", team_label=f"Class {class_id} XI")
        for index, class_id in enumerate(CLASS_IDS, start=1)
    }

    text = module_text_from_html_by_class(html_by_class, generated_on=datetime(2026, 10, 4).date())
    namespace: dict[str, object] = {}
    exec(text, namespace)

    assert text.startswith("# This file is generated by scripts/gen_ids.py.\n")
    assert namespace["CLASS_IDS"] == (1, 2, 3, 11, 6)
    assert namespace["FIRST_MATCH_DATES"] == {
        1: "01 Jan 2000",
        2: "02 Jan 2000",
        3: "03 Jan 2000",
        11: "04 Jan 2000",
        6: "05 Jan 2000",
    }
    assert namespace["TEAMS"][3] == {7: "Class 3 XI", 8: "Beta XI"}
    assert namespace["HOSTS"][6] == {1: "Hostland"}
    assert namespace["CONTINENTS"][1] == {2: "Asia"}
    assert namespace["TROPHIES"][2] == {12: "World Cup", 117: "Indian Premier League"}
    assert namespace["OPPOSITION_DIFFERS_FROM_TEAM_CLASSES"] == ()


def test_generator_records_classes_with_different_opposition_tables() -> None:
    html_by_class = {
        class_id: form_html(spanmin0=f"0{index} Jan 2000", team_label=f"Class {class_id} XI")
        for index, class_id in enumerate(CLASS_IDS, start=1)
    }
    html_by_class[3] = form_html(
        spanmin0="03 Jan 2000", team_label="Class 3 XI", opposition_label="Other XI"
    )

    text = module_text_from_html_by_class(html_by_class, generated_on=datetime(2026, 10, 4).date())
    namespace: dict[str, object] = {}
    exec(text, namespace)

    assert namespace["OPPOSITION_DIFFERS_FROM_TEAM_CLASSES"] == (3,)


def test_generator_emits_ruff_formatted_output_from_synthetic_forms() -> None:
    html_by_class = {
        class_id: form_html(spanmin0=f"0{index} Jan 2000", team_label=f"Class {class_id} XI")
        for index, class_id in enumerate(CLASS_IDS, start=1)
    }
    text = module_text_from_html_by_class(html_by_class, generated_on=datetime(2026, 10, 4).date())

    result = subprocess.run(
        [
            sys.executable,
            "-m",
            "ruff",
            "format",
            "--check",
            "--stdin-filename",
            "src/crickey/id_tables.py",
            "-",
        ],
        input=text,
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0, result.stderr


def test_builtin_spot_checks_from_statsguru_forms() -> None:
    assert id_tables.TEAMS[2][7] == "Pakistan"
    assert id_tables.TROPHIES[2][12] == "World Cup"
    assert id_tables.TROPHIES[6][117] == "Indian Premier League"
    assert id_tables.TEAMS[6][5799] == "Lahore Qalandars"
    assert lookup_team(2, "Pakistan").match.value == 7
    assert lookup_trophy(2, "World Cup").match.value == 12
    assert lookup_trophy(6, "Indian Premier League").match.value == 117
    assert lookup_team(6, "Lahore Qalandars").match.value == 5799


def test_builtin_lookup_tiers_resolve_acronyms_and_generic_names() -> None:
    expected_matches = (
        (lookup_trophy, 6, "IPL", 117),
        (lookup_trophy, 6, "PSL", 205),
        (lookup_team, 3, "USA", 11),
        (lookup_team, 1, "SA", 3),
        (lookup_trophy, 2, "Cricket World Cup", 12),
        (lookup_trophy, 2, "ICC Cricket World Cup", 12),
        (lookup_trophy, 3, "T20 World Cup", 89),
        (lookup_trophy, 11, "T20 World Cup", 89),
        (lookup_trophy, 2, "ODI World Cup", 12),
        (lookup_trophy, 2, "ODI World Cups", 12),
        (lookup_trophy, 2, "One-Day World Cup", 12),
        (lookup_trophy, 3, "T20I World Cup", 89),
        (lookup_trophy, 1, "Ashes Tests", 1),
        (lookup_trophy, 2, "World Cup ODIs", 12),
        (lookup_trophy, 3, "T20Is World Cup", 89),
    )

    for lookup, class_id, query, value in expected_matches:
        result = lookup(class_id, query)
        assert result.status == LookupStatus.MATCH
        assert result.match.value == value


def test_builtin_lookup_returns_candidates_for_collisions_and_unsafe_fuzzy_matches() -> None:
    big_bash = lookup_trophy(6, "Big Bash")
    team_sa = lookup_team(6, "SA")
    premier_league = lookup_trophy(6, "Premier League")
    australasia = lookup_continent(1, "Australasia")

    assert [candidate.value for candidate in big_bash.candidates] == [124, 158]
    assert {candidate.value for candidate in team_sa.candidates} == {3, 154, 571}
    assert premier_league.needs_clarification is True
    assert premier_league.match is None
    assert australasia.needs_clarification is True
    assert australasia.match is None
    assert lookup_trophy(3, "World T20").candidates[0].value == 89
    assert lookup_trophy(3, "ICC World T20").candidates[0].value == 89
    assert lookup_trophy(11, "Asia Cup").status == LookupStatus.NEEDS_CLARIFICATION
    assert lookup_team(2, "India A").match is None


def test_builtin_lookup_prefix_tier_resolves_unique_team_prefixes_only() -> None:
    assert lookup_team(2, "Aus").match.value == 2
    assert lookup_team(2, "Eng").match.value == 1
    assert lookup_team(2, "Pak").match.value == 7
    assert lookup_team(2, "Au").match is None

    ind = lookup_team(2, "Ind")
    sou = lookup_team(6, "Sou")

    assert ind.match is None
    assert [candidate.value for candidate in ind.candidates] == [4, 6]
    assert len(sou.candidates) == 5
    assert [candidate.score for candidate in sou.candidates] == sorted(
        (candidate.score for candidate in sou.candidates), reverse=True
    )
    assert lookup_continent(1, "Australasia").match is None


def test_name_lookup_exact_case_insensitive_and_fuzzy_matches() -> None:
    exact = lookup_team(2, "  pAKisTan ")
    fuzzy = lookup_team(2, "Pakstan")

    assert exact.status == LookupStatus.MATCH
    assert exact.match.value == 7
    assert fuzzy.status == LookupStatus.MATCH
    assert fuzzy.match.value == 7


def test_exact_tier_wins_before_containment_or_fuzzy_candidates() -> None:
    result = resolve_name(1, "trophy", "Cricket", {1: "Cricket", 2: "ICC Cricket"})

    assert result.status == LookupStatus.MATCH
    assert result.match.value == 1


def test_fuzzy_match_requires_clear_ratio_margin() -> None:
    result = resolve_name(1, "team", "Alpha Teem", {1: "Alpha Team", 2: "Alpha Teim"})

    assert result.needs_clarification is True
    assert result.match is None
    assert [candidate.value for candidate in result.candidates] == [1, 2]


def test_containment_resolves_only_when_unique_and_fuzzy_singletons_do_not() -> None:
    containment = resolve_name(1, "ground", "Eden Gardens", {1: "IND: Eden Gardens, Kolkata"})
    fuzzy = lookup_team(2, "India A")

    assert containment.status == LookupStatus.MATCH
    assert containment.match.value == 1
    assert fuzzy.match is None


def test_containment_candidates_are_ranked_by_wratio() -> None:
    result = resolve_name(1, "series", "Foo Bar", {1: "Foo Bar Baz", 2: "Bar Foo"})

    assert result.needs_clarification is True
    assert [candidate.value for candidate in result.candidates] == [2, 1]


def test_fuzzy_candidates_keep_score_filter() -> None:
    result = resolve_name(
        1,
        "team",
        "Alpha T",
        {
            1: "Alpha Tigers",
            2: "Alpha Lions",
            3: "Beta Bears",
            4: "Gamma Goats",
            5: "Delta Ducks",
            6: "Echo Eagles",
        },
    )

    assert [candidate.value for candidate in result.candidates] == [1, 2]


def test_synthetic_lookup_tiers_handle_acronym_collision_and_generic_words() -> None:
    acronym_collision = resolve_name(
        6,
        "trophy",
        "BBL",
        {124: "Big Bash League", 158: "Bogus Bash League"},
    )
    generic = resolve_name(
        3,
        "trophy",
        "Men's T20 World Cup",
        {89: "ICC Men's T20 World Cup", 1006: "ICC Men's T20 World Cup Qualifier"},
    )

    assert [candidate.value for candidate in acronym_collision.candidates] == [124, 158]
    assert generic.status == LookupStatus.MATCH
    assert generic.match.value == 89


def test_name_lookup_returns_candidates_for_ambiguous_and_unknown_names() -> None:
    ambiguous = resolve_name(1, "team", "alpha cc", {1: "Alpha CC", 2: "Alpha-CC"})
    unknown = resolve_name(1, "team", "zzzzzz", {7: "Pakistan", 6: "India", 2: "Australia"})

    assert ambiguous.needs_clarification is True
    assert [candidate.value for candidate in ambiguous.candidates] == [1, 2]
    assert unknown.needs_clarification is True
    assert 1 <= len(unknown.candidates) <= 3
    assert unknown.match is None


def test_on_demand_ground_series_and_involve_lookups_use_memory_source_and_cache() -> None:
    class_id = 3
    form_url = FORM_URL.format(class_id=class_id)
    player_url = INVOLVE_URL.format(
        class_id=class_id, search_field="search_player", query="babar+azam"
    )
    captain_url = INVOLVE_URL.format(
        class_id=class_id, search_field="search_captain", query="babar+azam"
    )
    source = MemoryPageSource(
        {
            form_url: form_html(),
            player_url: form_html(involve_field="player_involve"),
            captain_url: form_html(involve_field="captain_involve"),
        }
    )
    fetcher = Fetcher(settings(), clock=FakeClock(), page_source=source)
    resolver = StatsguruIdResolver(fetcher, budget=20)

    ground = run(resolver.lookup_ground(class_id, "alpha ground"))
    series = run(resolver.lookup_series(class_id, "Alpha Cup 2026"))
    player = run(resolver.lookup_player_involve(class_id, "babar azam"))
    captain = run(resolver.lookup_captain_involve(class_id, "babar azam"))
    cached_ground = run(resolver.lookup_ground(class_id, "Alpha Ground"))
    cached_player = run(resolver.lookup_player_involve(class_id, "Babar Azam"))

    assert ground.match.value == 701
    assert series.match.value == 801
    assert player.match.value == 56880
    assert player.match.kind == "player_involve"
    assert captain.match.value == 56880
    assert captain.match.kind == "captain_involve"
    assert player.match.name == "Babar Azam (PAK)"
    assert cached_ground.match.value == 701
    assert cached_player.match.value == 56880
    assert source.requests == [form_url, player_url, captain_url]


def test_on_demand_lookup_miss_refetches_once() -> None:
    class_id = 3
    form_url = FORM_URL.format(class_id=class_id)
    source = MemoryPageSource({form_url: form_html()})
    fetcher = Fetcher(settings(), clock=FakeClock(), page_source=source)
    resolver = StatsguruIdResolver(fetcher, budget=20)

    warm = run(resolver.lookup_ground(class_id, "Alpha Ground"))
    source.pages[form_url] = form_html(include_new_ground=True)
    result = run(resolver.lookup_ground(class_id, "New Ground"))

    assert warm.match.value == 701
    assert result.match.value == 702
    assert source.requests == [form_url, form_url]


def test_on_demand_series_without_season_returns_edition_candidates() -> None:
    class_id = 3
    form_url = FORM_URL.format(class_id=class_id)
    source = MemoryPageSource(
        {
            form_url: form_html(
                extra_series_options=(
                    '<option value="901">New Zealand in India T20I Series, 2012</option>'
                    '<option value="902">New Zealand in India T20I Series, 2017/18</option>'
                    '<option value="903">New Zealand in India T20I Series, 2021/22</option>'
                    '<option value="904">New Zealand in India T20I Series, 2022/23</option>'
                )
            )
        }
    )
    fetcher = Fetcher(settings(), clock=FakeClock(), page_source=source)
    resolver = StatsguruIdResolver(fetcher, budget=20)

    result = run(resolver.lookup_series(class_id, "New Zealand in India T20I Series"))

    assert result.needs_clarification is True
    assert [candidate.value for candidate in result.candidates] == [901, 902, 903, 904]
    assert source.requests == [form_url]


def test_on_demand_unique_containment_match_uses_cache_without_refetch() -> None:
    class_id = 3
    form_url = FORM_URL.format(class_id=class_id)
    source = MemoryPageSource({form_url: form_html(ground_label="IND: Eden Gardens, Kolkata")})
    fetcher = Fetcher(settings(), clock=FakeClock(), page_source=source)
    resolver = StatsguruIdResolver(fetcher, budget=20)

    first = run(resolver.lookup_ground(class_id, "Eden Gardens"))
    second = run(resolver.lookup_ground(class_id, "Eden Gardens"))

    assert first.match.value == 701
    assert second.match.value == 701
    assert source.requests == [form_url]


def test_on_demand_cached_ambiguous_containment_does_not_refetch() -> None:
    class_id = 3
    form_url = FORM_URL.format(class_id=class_id)
    source = MemoryPageSource(
        {
            form_url: form_html(
                extra_ground_options=(
                    '<option value="702">UAE: Dubai International Cricket Stadium</option>'
                    '<option value="703">UAE: Dubai Sports City Cricket Stadium</option>'
                )
            )
        }
    )
    fetcher = Fetcher(settings(), clock=FakeClock(), page_source=source)
    resolver = StatsguruIdResolver(fetcher, budget=20)

    warm = run(resolver.lookup_ground(class_id, "Alpha Ground"))
    ambiguous = run(resolver.lookup_ground(class_id, "Dubai"))

    assert warm.match.value == 701
    assert ambiguous.needs_clarification is True
    assert [candidate.value for candidate in ambiguous.candidates] == [702, 703]
    assert source.requests == [form_url]


def test_on_demand_form_url_cache_miss_refetches_across_fields() -> None:
    class_id = 3
    form_url = FORM_URL.format(class_id=class_id)
    source = MemoryPageSource({form_url: form_html()})
    fetcher = Fetcher(settings(), clock=FakeClock(), page_source=source)
    resolver = StatsguruIdResolver(fetcher, budget=20)

    warm = run(resolver.lookup_ground(class_id, "Alpha Ground"))
    source.pages[form_url] = form_html(include_new_series=True)
    result = run(resolver.lookup_series(class_id, "New Series"))

    assert warm.match.value == 701
    assert result.match.value == 802
    assert source.requests == [form_url, form_url]


def test_on_demand_form_cache_keys_include_class() -> None:
    class_2_url = FORM_URL.format(class_id=2)
    class_3_url = FORM_URL.format(class_id=3)
    source = MemoryPageSource(
        {
            class_2_url: form_html(ground_value=701, ground_label="AAA: Alpha Ground"),
            class_3_url: form_html(ground_value=703, ground_label="AAA: Alpha Ground"),
        }
    )
    fetcher = Fetcher(settings(), clock=FakeClock(), page_source=source)
    resolver = StatsguruIdResolver(fetcher, budget=20)

    class_2 = run(resolver.lookup_ground(2, "Alpha Ground"))
    class_3 = run(resolver.lookup_ground(3, "Alpha Ground"))

    assert class_2.match.value == 701
    assert class_3.match.value == 703
    assert source.requests == [class_2_url, class_3_url]


def test_on_demand_involve_cached_miss_refetches_once() -> None:
    class_id = 3
    player_url = INVOLVE_URL.format(
        class_id=class_id, search_field="search_player", query="babar+azam"
    )
    source = MemoryPageSource({player_url: form_html()})
    fetcher = Fetcher(settings(), clock=FakeClock(), page_source=source)
    resolver = StatsguruIdResolver(fetcher, budget=20)

    miss = run(resolver.lookup_player_involve(class_id, "babar azam"))
    source.pages[player_url] = form_html(involve_field="player_involve")
    result = run(resolver.lookup_player_involve(class_id, "babar azam"))

    assert miss.match is None
    assert result.match.value == 56880
    assert source.requests == [player_url, player_url]


def test_on_demand_lookup_first_miss_does_not_refetch() -> None:
    class_id = 3
    form_url = FORM_URL.format(class_id=class_id)
    source = MemoryPageSource({form_url: form_html()})
    fetcher = Fetcher(settings(), clock=FakeClock(), page_source=source)
    resolver = StatsguruIdResolver(fetcher, budget=20)

    result = run(resolver.lookup_ground(class_id, "New Ground"))

    assert result.needs_clarification is True
    assert result.match is None
    assert source.requests == [form_url]


def test_on_demand_lookup_uses_lookup_freshness_not_recent_ttl() -> None:
    class_id = 3
    form_url = FORM_URL.format(class_id=class_id)
    clock = FakeClock()
    source = MemoryPageSource({form_url: form_html()})
    fetcher = Fetcher(settings(), clock=clock, page_source=source)

    warm = run(StatsguruIdResolver(fetcher, budget=20).lookup_ground(class_id, "Alpha Ground"))
    clock.monotonic_time += settings().recent_ttl.total_seconds() + 1
    cached = run(StatsguruIdResolver(fetcher, budget=20).lookup_ground(class_id, "Alpha Ground"))

    assert warm.match.value == 701
    assert cached.match.value == 701
    assert source.requests == [form_url]


def test_involve_lookup_with_no_hits_returns_empty_clarification() -> None:
    class_id = 3
    player_url = INVOLVE_URL.format(class_id=class_id, search_field="search_player", query="nobody")
    source = MemoryPageSource({player_url: form_html()})
    fetcher = Fetcher(settings(), clock=FakeClock(), page_source=source)
    resolver = StatsguruIdResolver(fetcher, budget=20)

    result = run(resolver.lookup_player_involve(class_id, "nobody"))

    assert result.needs_clarification is True
    assert result.match is None
    assert result.candidates == ()
    assert source.requests == [player_url]


def test_resolver_accepts_shared_fetch_call_and_progress_stream() -> None:
    async def scenario() -> tuple[object, object, list[tuple[float, str]], list[str]]:
        class_id = 3
        form_url = FORM_URL.format(class_id=class_id)
        player_url = INVOLVE_URL.format(
            class_id=class_id, search_field="search_player", query="babar+azam"
        )
        source = MemoryPageSource(
            {form_url: form_html(), player_url: form_html(involve_field="player_involve")}
        )
        progress_events: list[tuple[float, str]] = []
        fetcher = Fetcher(settings(), clock=FakeClock(), page_source=source)
        resolver = StatsguruIdResolver(fetcher, budget=20)

        async with fetcher.call(
            budget=20, progress=lambda seconds, reason: progress_events.append((seconds, reason))
        ) as call:
            ground = await resolver.lookup_ground(class_id, "Alpha Ground", call=call)
            player = await resolver.lookup_player_involve(class_id, "babar azam", call=call)
        return ground, player, progress_events, source.requests

    ground, player, progress_events, requests = run(scenario())

    assert ground.match.value == 701
    assert player.match.value == 56880
    assert progress_events == [(2.0, "spacing requests politely")]
    assert requests == [
        FORM_URL.format(class_id=3),
        INVOLVE_URL.format(class_id=3, search_field="search_player", query="babar+azam"),
    ]
