from __future__ import annotations

import asyncio
import importlib.util
import sys
from collections.abc import Awaitable
from datetime import UTC, datetime, timedelta
from pathlib import Path

from crickey import id_tables
from crickey.fetcher import Fetcher, MemoryPageSource
from crickey.ids import (
    FORM_URL,
    INVOLVE_URL,
    LookupStatus,
    StatsguruIdResolver,
    lookup_team,
    lookup_trophy,
    resolve_name,
)
from crickey.settings import Settings

_GEN_IDS_SPEC = importlib.util.spec_from_file_location(
    "gen_ids_for_tests", Path(__file__).parents[1] / "scripts" / "gen_ids.py"
)
assert _GEN_IDS_SPEC is not None and _GEN_IDS_SPEC.loader is not None
_GEN_IDS_MODULE = importlib.util.module_from_spec(_GEN_IDS_SPEC)
sys.modules[_GEN_IDS_SPEC.name] = _GEN_IDS_MODULE
_GEN_IDS_SPEC.loader.exec_module(_GEN_IDS_MODULE)
CLASS_IDS = _GEN_IDS_MODULE.CLASS_IDS
module_text_from_html_by_class = _GEN_IDS_MODULE.module_text_from_html_by_class


class FakeClock:
    def __init__(self) -> None:
        self.monotonic_time = 0.0
        self.wall_time = datetime(2026, 10, 4, tzinfo=UTC)
        self.sleeps: list[float] = []

    def monotonic(self) -> float:
        return self.monotonic_time

    def now(self) -> datetime:
        return self.wall_time + timedelta(seconds=self.monotonic_time)

    async def sleep(self, seconds: float) -> None:
        self.sleeps.append(seconds)
        self.monotonic_time += seconds
        await asyncio.sleep(0)


def run(coro: Awaitable[object]) -> object:
    return asyncio.run(coro)


def settings() -> Settings:
    return Settings(min_interval=timedelta(seconds=2), max_retries=0)


def form_html(
    *,
    spanmin0: str = "01 Jan 2000",
    team_label: str = "Alpha XI",
    ground_label: str = "AAA: Alpha Ground",
    series_label: str = "Alpha Cup, 2026",
    include_new_ground: bool = False,
    involve_field: str | None = None,
) -> str:
    new_ground = '<option value="702">BBB: New Ground</option>' if include_new_ground else ""
    involve = ""
    if involve_field is not None:
        involve = (
            f'<input type="checkbox" name="{involve_field}" value="56880" checked>'
            ' found using "babar azam": Babar Azam'
        )
    return f"""
    <html><body><form name="gurumenu">
    <input type="hidden" name="spanmin0" value="{spanmin0}">
    <select name="team">
      <option value="">all teams</option>
      <option value="7">{team_label}</option>
      <option value="8">Beta XI</option>
    </select>
    <select name="opposition">
      <option value="">all teams</option>
      <option value="7">{team_label}</option>
      <option value="8">Beta XI</option>
    </select>
    <select name="host">
      <option value="">all countries</option><option value="1">Hostland</option>
    </select>
    <select name="continent">
      <option value="">all continents</option><option value="2">Asia</option>
    </select>
    <select name="trophy">
      <option value="">all tournaments</option>
      <option value="12">World Cup</option>
      <option value="117">Indian Premier League</option>
    </select>
    <select name="ground">
      <option value="">all grounds</option>
      <option value="701">{ground_label}</option>{new_ground}
    </select>
    <select name="series">
      <option value="">all series</option><option value="801">{series_label}</option>
    </select>
    {involve}
    </form></body></html>
    """


def test_generator_builds_exact_tables_from_synthetic_forms() -> None:
    html_by_class = {
        class_id: form_html(spanmin0=f"0{index} Jan 2000", team_label=f"Class {class_id} XI")
        for index, class_id in enumerate(CLASS_IDS, start=1)
    }

    text = module_text_from_html_by_class(html_by_class, generated_on=datetime(2026, 10, 4).date())
    namespace: dict[str, object] = {}
    exec(text, namespace)

    assert text.startswith("# This file is generated by scripts/gen_ids.py.\n")
    assert namespace["CLASS_IDS"] == (1, 2, 3, 11, 6)
    assert namespace["FIRST_MATCH_DATES"] == {
        1: "01 Jan 2000",
        2: "02 Jan 2000",
        3: "03 Jan 2000",
        11: "04 Jan 2000",
        6: "05 Jan 2000",
    }
    assert namespace["TEAMS"][3] == {7: "Class 3 XI", 8: "Beta XI"}
    assert namespace["HOSTS"][6] == {1: "Hostland"}
    assert namespace["CONTINENTS"][1] == {2: "Asia"}
    assert namespace["TROPHIES"][2] == {12: "World Cup", 117: "Indian Premier League"}
    assert namespace["OPPOSITION_DIFFERS_FROM_TEAM_CLASSES"] == ()


def test_builtin_spot_checks_from_statsguru_forms() -> None:
    assert id_tables.TEAMS[2][7] == "Pakistan"
    assert id_tables.TROPHIES[2][12] == "World Cup"
    assert id_tables.TROPHIES[6][117] == "Indian Premier League"
    assert id_tables.TEAMS[6][5799] == "Lahore Qalandars"
    assert lookup_team(2, "Pakistan").match.value == 7
    assert lookup_trophy(2, "World Cup").match.value == 12
    assert lookup_trophy(6, "Indian Premier League").match.value == 117
    assert lookup_team(6, "Lahore Qalandars").match.value == 5799


def test_name_lookup_exact_case_insensitive_and_fuzzy_matches() -> None:
    exact = lookup_team(2, "  pAKisTan ")
    fuzzy = lookup_team(2, "Pakstan")

    assert exact.status == LookupStatus.MATCH
    assert exact.match.value == 7
    assert fuzzy.status == LookupStatus.MATCH
    assert fuzzy.match.value == 7


def test_name_lookup_returns_candidates_for_ambiguous_and_unknown_names() -> None:
    ambiguous = resolve_name(1, "team", "alpha cc", {1: "Alpha CC", 2: "Alpha-CC"})
    unknown = resolve_name(1, "team", "zzzzzz", {7: "Pakistan", 6: "India", 2: "Australia"})

    assert ambiguous.needs_clarification is True
    assert [candidate.value for candidate in ambiguous.candidates] == [1, 2]
    assert unknown.needs_clarification is True
    assert 1 <= len(unknown.candidates) <= 3
    assert unknown.match is None


def test_on_demand_ground_series_and_involve_lookups_use_memory_source_and_cache() -> None:
    class_id = 3
    form_url = FORM_URL.format(class_id=class_id)
    player_url = INVOLVE_URL.format(
        class_id=class_id, search_field="search_player", query="babar+azam"
    )
    captain_url = INVOLVE_URL.format(
        class_id=class_id, search_field="search_captain", query="babar+azam"
    )
    source = MemoryPageSource(
        {
            form_url: form_html(),
            player_url: form_html(involve_field="player_involve"),
            captain_url: form_html(involve_field="captain_involve"),
        }
    )
    fetcher = Fetcher(settings(), clock=FakeClock(), page_source=source)
    resolver = StatsguruIdResolver(fetcher, budget=20)

    ground = run(resolver.lookup_ground(class_id, "alpha ground"))
    series = run(resolver.lookup_series(class_id, "Alpha Cup 2026"))
    player = run(resolver.lookup_player_involve(class_id, "babar azam"))
    captain = run(resolver.lookup_captain_involve(class_id, "babar azam"))
    cached_ground = run(resolver.lookup_ground(class_id, "Alpha Ground"))
    cached_player = run(resolver.lookup_player_involve(class_id, "Babar Azam"))

    assert ground.match.value == 701
    assert series.match.value == 801
    assert player.match.value == 56880
    assert player.match.kind == "player_involve"
    assert captain.match.value == 56880
    assert captain.match.kind == "captain_involve"
    assert cached_ground.match.value == 701
    assert cached_player.match.value == 56880
    assert source.requests == [form_url, player_url, captain_url]


def test_on_demand_lookup_miss_refetches_once() -> None:
    class_id = 3
    form_url = FORM_URL.format(class_id=class_id)
    source = MemoryPageSource({form_url: form_html()})
    fetcher = Fetcher(settings(), clock=FakeClock(), page_source=source)
    resolver = StatsguruIdResolver(fetcher, budget=20)

    result = run(resolver.lookup_ground(class_id, "New Ground"))

    assert result.needs_clarification is True
    assert result.match is None
    assert source.requests == [form_url, form_url]
