from __future__ import annotations

import argparse
import asyncio
from collections.abc import Mapping
from datetime import date
from pathlib import Path

from crickey.fetcher import Fetcher, Freshness
from crickey.parsers import FilterForm, FormOption, parse_filter_form
from crickey.settings import Settings

CLASS_IDS = (1, 2, 3, 11, 6)
FORM_URL = "https://stats.cricinfo.com/ci/engine/stats/index.html?class={class_id};filter=advanced;type=batting"
GENERATED_HEADER = (
    "# This file is generated by scripts/gen_ids.py.\n"
    "# Generated on {generated_on}. Do not edit by hand; "
    "rerun `uv run python scripts/gen_ids.py`.\n\n"
    "from __future__ import annotations\n\n"
)


def module_text_from_html_by_class(
    html_by_class: Mapping[int, str], *, generated_on: date | None = None
) -> str:
    """Return deterministic Python source for built-in Statsguru ID tables."""
    generated_on = date.today() if generated_on is None else generated_on
    forms = {class_id: parse_filter_form(html_by_class[class_id]) for class_id in CLASS_IDS}
    first_match_dates = {
        class_id: _required_hidden(form, "spanmin0") for class_id, form in forms.items()
    }
    teams: dict[int, dict[int, str]] = {}
    hosts: dict[int, dict[int, str]] = {}
    continents: dict[int, dict[int, str]] = {}
    trophies: dict[int, dict[int, str]] = {}
    opposition_differs: list[int] = []
    for class_id, form in forms.items():
        team_table = _table(form, "team")
        opposition_table = _table(form, "opposition")
        if team_table != opposition_table:
            opposition_differs.append(class_id)
        teams[class_id] = team_table
        hosts[class_id] = _table(form, "host")
        continents[class_id] = _table(form, "continent")
        trophies[class_id] = _table(form, "trophy")

    return "".join(
        (
            GENERATED_HEADER.format(generated_on=generated_on.isoformat()),
            _emit_tuple("CLASS_IDS", CLASS_IDS),
            _emit_dict("FIRST_MATCH_DATES", first_match_dates),
            _emit_nested_dict("TEAMS", teams),
            _emit_nested_dict("HOSTS", hosts),
            _emit_nested_dict("CONTINENTS", continents),
            _emit_nested_dict("TROPHIES", trophies),
            _emit_tuple("OPPOSITION_DIFFERS_FROM_TEAM_CLASSES", tuple(opposition_differs)),
        )
    )


def _required_hidden(form: FilterForm, name: str) -> str:
    value = form.hidden_fields.get(name)
    if not value:
        raise ValueError(f"advanced form is missing hidden {name!r}")
    return value


def _table(form: FilterForm, field: str) -> dict[int, str]:
    options = form.select_lists.get(field)
    if options is None:
        raise ValueError(f"advanced form is missing select {field!r}")
    table: dict[int, str] = {}
    for option in options:
        if not option.value:
            continue
        table[_option_int(option, field)] = option.label
    if not table:
        raise ValueError(f"advanced form select {field!r} has no ID values")
    return table


def _option_int(option: FormOption, field: str) -> int:
    try:
        return int(option.value)
    except ValueError as error:
        raise ValueError(
            f"{field!r} option {option.label!r} has non-integer value {option.value!r}"
        ) from error


def _emit_tuple(name: str, values: tuple[int, ...]) -> str:
    return f"{name}: tuple[int, ...] = {values!r}\n\n"


def _emit_dict(name: str, values: Mapping[int, str]) -> str:
    lines = [f"{name}: dict[int, str] = {{\n"]
    for key in sorted(values):
        lines.append(f"    {key!r}: {values[key]!r},\n")
    lines.append("}\n\n")
    return "".join(lines)


def _emit_nested_dict(name: str, values: Mapping[int, Mapping[int, str]]) -> str:
    lines = [f"{name}: dict[int, dict[int, str]] = {{\n"]
    for class_id in CLASS_IDS:
        lines.append(f"    {class_id!r}: {{\n")
        for item_id in sorted(values[class_id]):
            lines.append(f"        {item_id!r}: {values[class_id][item_id]!r},\n")
        lines.append("    },\n")
    lines.append("}\n\n")
    return "".join(lines)


async def _fetch_html_by_class(output_dir: Path | None) -> dict[int, str]:
    fetcher = Fetcher(Settings())
    html_by_class: dict[int, str] = {}
    try:
        async with fetcher.call(budget=120) as call:
            for class_id in CLASS_IDS:
                url = FORM_URL.format(class_id=class_id)
                html = await call.fetch(url, freshness=Freshness.LOOKUP)
                html_by_class[class_id] = html
                if output_dir is not None:
                    output_dir.mkdir(parents=True, exist_ok=True)
                    page_name = f"gen_ids_class_{class_id}_advanced_batting.html"
                    (output_dir / page_name).write_text(html, encoding="utf-8")
                    _append_index(output_dir / "INDEX.md", page_name, url)
    finally:
        await fetcher.aclose()
    return html_by_class


def _append_index(index_path: Path, page_name: str, url: str) -> None:
    line = f"- {date.today().isoformat()} `{page_name}`: {url}\n"
    if index_path.exists() and line in index_path.read_text(encoding="utf-8"):
        return
    with index_path.open("a", encoding="utf-8") as handle:
        handle.write(line)


async def _main_async(args: argparse.Namespace) -> None:
    html_by_class = await _fetch_html_by_class(args.save_pages)
    text = module_text_from_html_by_class(html_by_class, generated_on=date.today())
    args.output.write_text(text, encoding="utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate crickey's built-in Statsguru ID tables.")
    parser.add_argument("--output", type=Path, default=Path("src/crickey/id_tables.py"))
    parser.add_argument("--save-pages", type=Path, default=Path(".local/pages"))
    args = parser.parse_args()
    asyncio.run(_main_async(args))


if __name__ == "__main__":
    main()
