from __future__ import annotations

import argparse
import asyncio
import pprint
import subprocess
import sys
from collections.abc import Mapping
from pathlib import Path

from crickey.parsers import FilterForm, FormOption, parse_filter_form

try:
    from scripts.statsguru_pages import (
        CLASS_IDS,
        STAT_TYPES,
        catalog_requests,
        fetch_lookup_pages,
        read_lookup_pages,
    )
except ModuleNotFoundError:  # pragma: no cover - direct script execution
    sys.path.append(str(Path(__file__).resolve().parent))
    from statsguru_pages import (
        CLASS_IDS,
        STAT_TYPES,
        catalog_requests,
        fetch_lookup_pages,
        read_lookup_pages,
    )

GENERATED_HEADER = (
    "# This file is generated by scripts/gen_query_catalog.py.\n"
    "# Do not edit by hand; rerun `uv run python scripts/gen_query_catalog.py`.\n\n"
    "from __future__ import annotations\n\n"
)
QUERY_ONLY_FIELDS = {
    "groupby",
    "orderby",
    "orderbyad",
    "qualmax1",
    "qualmin1",
    "qualval1",
    "size",
    "submit",
    "submit_reset",
    "submit_results",
    "type",
    "view",
}
DIRECT_PERIOD_FIELDS = {"spanmin1", "spanmax1"}
SPECIAL_SELECT_PREFIXES = ("havingselect_", "orderbyselect_")
QUERY_VIEWS = {
    "aggregate": {"", "match", "results", "series", "ground", "host", "year", "season", "extras"},
    "allround": {
        "",
        "innings",
        "match",
        "results",
        "awards",
        "series",
        "ground",
        "host",
        "opposition",
        "year",
        "season",
    },
    "batting": {"", "innings", "match", "series", "ground", "host", "opposition", "year", "season"},
    "bowling": {"", "innings", "match", "series", "ground", "host", "opposition", "year", "season"},
    "fielding": {
        "",
        "innings",
        "match",
        "series",
        "ground",
        "host",
        "opposition",
        "year",
        "season",
    },
    "fow": {"", "innings", "match", "series", "ground", "host", "opposition", "year", "season"},
    "team": {
        "",
        "innings",
        "match",
        "results",
        "series",
        "ground",
        "host",
        "opposition",
        "year",
        "season",
        "extras",
        "extras_innings",
    },
}
PLAYER_PAGE_VIEW_GROUPS = {
    "allround": {
        "",
        "innings",
        "match",
        "cumulative",
        "reverse_cumulative",
        "series",
        "ground",
        "results",
        "awards_match",
        "awards_series",
    },
    "batting": {
        "",
        "innings",
        "match",
        "cumulative",
        "reverse_cumulative",
        "series",
        "ground",
        "results",
        "awards_match",
        "awards_series",
        "fow_summary",
        "fow_list",
        "dismissal_summary",
        "bowler_summary",
        "fielder_summary",
        "dismissal_list",
    },
    "bowling": {
        "",
        "innings",
        "match",
        "cumulative",
        "reverse_cumulative",
        "series",
        "ground",
        "results",
        "awards_match",
        "awards_series",
        "dismissal_summary",
        "batsman_summary",
        "fielder_summary",
        "dismissal_list",
    },
    "fielding": {
        "",
        "innings",
        "match",
        "cumulative",
        "reverse_cumulative",
        "series",
        "ground",
        "results",
        "awards_match",
        "awards_series",
        "dismissal_summary",
        "batsman_summary",
        "bowler_summary",
        "dismissal_list",
    },
}


def module_text_from_pages(
    advanced_html: Mapping[tuple[int, str], str],
    player_html: Mapping[int, str],
) -> str:
    forms = {
        class_id: {
            stat_type: parse_filter_form(advanced_html[(class_id, stat_type)])
            for stat_type in STAT_TYPES
        }
        for class_id in CLASS_IDS
    }
    player_forms = {class_id: parse_filter_form(player_html[class_id]) for class_id in CLASS_IDS}

    type_field_kinds: dict[int, dict[str, dict[str, str]]] = {}
    multi_fields: dict[int, dict[str, list[str]]] = {}
    type_views: dict[int, dict[str, list[str]]] = {}
    type_groupbys: dict[int, dict[str, list[str]]] = {}
    qual_fields: dict[int, dict[str, dict[str, list[str]]]] = {}
    sort_fields: dict[int, dict[str, dict[str, list[str]]]] = {}
    range_val_fields: dict[int, dict[str, dict[str, str]]] = {}
    range_limits: dict[int, dict[str, dict[str, tuple[int, int]]]] = {}
    choice_values: dict[int, dict[str, dict[str, dict[str, str]]]] = {}
    quickpick_fields: dict[int, dict[str, list[str]]] = {}

    for class_id, by_type in forms.items():
        type_field_kinds[class_id] = {}
        multi_fields[class_id] = {}
        type_views[class_id] = {}
        type_groupbys[class_id] = {}
        qual_fields[class_id] = {}
        sort_fields[class_id] = {}
        range_val_fields[class_id] = {}
        range_limits[class_id] = {}
        choice_values[class_id] = {}
        quickpick_fields[class_id] = {}
        for stat_type, form in by_type.items():
            type_field_kinds[class_id][stat_type] = _field_kinds(form)
            multi_fields[class_id][stat_type] = sorted(form.checkbox_lists)
            views = _views(form, stat_type)
            type_views[class_id][stat_type] = views
            type_groupbys[class_id][stat_type] = _non_empty_values(
                form.select_lists.get("groupby", ())
            )
            qual_fields[class_id][stat_type] = _special_fields(form.minimum_lists, stat_type, views)
            sort_fields[class_id][stat_type] = _special_fields(form.sort_lists, stat_type, views)
            range_val_fields[class_id][stat_type] = _range_val_fields(form)
            range_limits[class_id][stat_type] = _range_limits(form)
            choice_values[class_id][stat_type] = _choice_values(form)
            quickpick_fields[class_id][stat_type] = sorted(
                field for field in form.select_lists if field.endswith("quickpick")
            )

    player_page_views = {
        class_id: _player_page_views(form) for class_id, form in player_forms.items()
    }
    player_page_choice_values = {
        class_id: {"batting": _choice_values(form)} for class_id, form in player_forms.items()
    }

    text = (
        "".join(
            (
                GENERATED_HEADER,
                _emit_tuple("CLASS_IDS", CLASS_IDS),
                _emit_tuple("STAT_TYPES", STAT_TYPES),
                _emit_nested("TYPE_FIELD_KINDS", type_field_kinds),
                _emit_nested("MULTI_FIELDS", multi_fields),
                _emit_nested("TYPE_VIEWS", type_views),
                _emit_nested("TYPE_GROUPBYS", type_groupbys),
                _emit_nested("QUAL_FIELDS", qual_fields),
                _emit_nested("SORT_FIELDS", sort_fields),
                _emit_nested("RANGE_VAL_FIELDS", range_val_fields),
                _emit_nested("RANGE_LIMITS", range_limits),
                _emit_nested("CHOICE_VALUES", choice_values),
                _emit_nested("QUICKPICK_FIELDS", quickpick_fields),
                _emit_nested("PLAYER_PAGE_VIEWS", player_page_views),
                _emit_nested("PLAYER_PAGE_CHOICE_VALUES", player_page_choice_values),
            )
        ).rstrip()
        + "\n"
    )
    return _format_module_text(text)


def _field_kinds(form: FilterForm) -> dict[str, str]:
    fields: dict[str, str] = {}
    for control in form.controls:
        if (
            control.kind == "hidden"
            or control.name in QUERY_ONLY_FIELDS
            or control.name in DIRECT_PERIOD_FIELDS
            or control.name.endswith("val1")
        ):
            continue
        fields.setdefault(control.name, control.kind)
    return dict(sorted(fields.items()))


def _views(form: FilterForm, stat_type: str) -> list[str]:
    seen = []
    for control in form.controls:
        if control.name == "view" and control.value in QUERY_VIEWS[stat_type]:
            if control.value not in seen:
                seen.append(control.value or "")
    return seen


def _player_page_views(form: FilterForm) -> dict[str, list[str]]:
    all_views = [control.value or "" for control in form.controls if control.name == "view"]
    grouped: dict[str, list[str]] = {}
    for stat_type, allowed in PLAYER_PAGE_VIEW_GROUPS.items():
        grouped[stat_type] = []
        for view in all_views:
            if view in allowed and view not in grouped[stat_type]:
                grouped[stat_type].append(view)
    return grouped


def _special_fields(
    lists: Mapping[tuple[str, str], tuple[FormOption, ...]], stat_type: str, views: list[str]
) -> dict[str, list[str]]:
    result: dict[str, list[str]] = {}
    for view in views:
        form_view = view or "default"
        result[view] = _non_empty_values(lists.get((stat_type, form_view), ()))
    return result


def _range_val_fields(form: FilterForm) -> dict[str, str]:
    result = {}
    for name, value in form.hidden_fields.items():
        if name.endswith("val1") and name != "spanval1":
            result[name[:-4]] = value
    return dict(sorted(result.items()))


def _range_limits(form: FilterForm) -> dict[str, tuple[int, int]]:
    limits = {}
    for name, value in form.hidden_fields.items():
        if not name.endswith("min0") or name == "spanmin0":
            continue
        prefix = name[:-4]
        max_value = form.hidden_fields.get(f"{prefix}max0")
        if max_value is None:
            continue
        low = int(value)
        high = int(max_value)
        limits[f"{prefix}min1"] = (low, high)
        limits[f"{prefix}max1"] = (low, high)
    return dict(sorted(limits.items()))


def _choice_values(form: FilterForm) -> dict[str, dict[str, str]]:
    choices: dict[str, dict[str, str]] = {}
    for field, options in {
        **form.checkbox_lists,
        **form.radio_lists,
        **{
            key: options
            for key, options in form.select_lists.items()
            if not key.startswith(SPECIAL_SELECT_PREFIXES)
        },
    }.items():
        table = {
            option.value: _clean_label(option.label)
            for option in options
            if option.value
            and field not in QUERY_ONLY_FIELDS
            and field
            not in {
                "team",
                "opposition",
                "host",
                "continent",
                "ground",
                "season",
                "series",
                "trophy",
            }
        }
        if table:
            choices[field] = dict(sorted(table.items()))
    return dict(sorted(choices.items()))


def _non_empty_values(options: tuple[FormOption, ...]) -> list[str]:
    return [option.value for option in options if option.value]


def _clean_label(label: str) -> str:
    return " ".join(label.split())


def _emit_tuple(name: str, values: tuple[object, ...]) -> str:
    return f"{name} = {_literal(values)}\n\n"


def _emit_nested(name: str, value: object) -> str:
    return f"{name} = {_literal(value)}\n\n"


def _literal(value: object) -> str:
    return pprint.pformat(value, sort_dicts=True, width=100)


def _format_module_text(text: str) -> str:
    result = subprocess.run(
        [
            sys.executable,
            "-m",
            "ruff",
            "format",
            "--stdin-filename",
            "src/crickey/query_catalog.py",
            "-",
        ],
        input=text,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr or result.stdout)
    return result.stdout


def _split_pages(pages: Mapping[str, str]) -> tuple[dict[tuple[int, str], str], dict[int, str]]:
    advanced: dict[tuple[int, str], str] = {}
    players: dict[int, str] = {}
    for key, html in pages.items():
        class_text, kind = key.split(":", 1)
        if kind == "player":
            players[int(class_text)] = html
        else:
            advanced[(int(class_text), kind)] = html
    return advanced, players


async def _main_async(args: argparse.Namespace) -> None:
    pages = (
        read_lookup_pages(catalog_requests(), input_pages=args.input_pages)
        if args.input_pages is not None
        else await fetch_lookup_pages(catalog_requests(), save_pages=args.save_pages, budget=900)
    )
    advanced, players = _split_pages(pages)
    args.output.write_text(
        module_text_from_pages(advanced, players), encoding="utf-8", newline="\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate crickey's Statsguru query catalog.")
    parser.add_argument("--output", type=Path, default=Path("src/crickey/query_catalog.py"))
    parser.add_argument("--save-pages", type=Path, default=Path(".local/pages"))
    parser.add_argument("--input-pages", type=Path)
    args = parser.parse_args()
    asyncio.run(_main_async(args))


if __name__ == "__main__":
    main()
