from __future__ import annotations

import argparse
import asyncio
import json
import sys
from collections.abc import Mapping
from datetime import date
from pathlib import Path

from crickey.parsers import FilterForm, FormOption, parse_filter_form

try:
    from scripts.statsguru_pages import (
        CLASS_IDS,
        fetch_lookup_pages,
        ids_requests,
        read_lookup_pages,
    )
except ModuleNotFoundError:  # pragma: no cover - direct script execution
    sys.path.append(str(Path(__file__).resolve().parent))
    from statsguru_pages import CLASS_IDS, fetch_lookup_pages, ids_requests, read_lookup_pages

GENERATED_HEADER = (
    "# This file is generated by scripts/gen_ids.py.\n"
    "# Generated on {generated_on}. Do not edit by hand; "
    "rerun `uv run python scripts/gen_ids.py`.\n\n"
    "from __future__ import annotations\n\n"
)


def module_text_from_html_by_class(
    html_by_class: Mapping[int, str], *, generated_on: date | None = None
) -> str:
    """Return deterministic Python source for built-in Statsguru ID tables."""
    generated_on = date.today() if generated_on is None else generated_on
    forms = {class_id: parse_filter_form(html_by_class[class_id]) for class_id in CLASS_IDS}
    first_match_dates = {
        class_id: _required_hidden(form, "spanmin0") for class_id, form in forms.items()
    }
    teams: dict[int, dict[int, str]] = {}
    hosts: dict[int, dict[int, str]] = {}
    continents: dict[int, dict[int, str]] = {}
    trophies: dict[int, dict[int, str]] = {}
    opposition_differs: list[int] = []
    for class_id, form in forms.items():
        team_table = _table(form, "team")
        opposition_table = _table(form, "opposition")
        if team_table != opposition_table:
            opposition_differs.append(class_id)
        teams[class_id] = team_table
        hosts[class_id] = _table(form, "host")
        continents[class_id] = _table(form, "continent")
        trophies[class_id] = _table(form, "trophy")

    return (
        "".join(
            (
                GENERATED_HEADER.format(generated_on=generated_on.isoformat()),
                _emit_tuple("CLASS_IDS", CLASS_IDS),
                _emit_dict("FIRST_MATCH_DATES", first_match_dates),
                _emit_nested_dict("TEAMS", teams),
                _emit_nested_dict("HOSTS", hosts),
                _emit_nested_dict("CONTINENTS", continents),
                _emit_nested_dict("TROPHIES", trophies),
                _emit_tuple("OPPOSITION_DIFFERS_FROM_TEAM_CLASSES", tuple(opposition_differs)),
            )
        ).rstrip()
        + "\n"
    )


def _required_hidden(form: FilterForm, name: str) -> str:
    value = form.hidden_fields.get(name)
    if not value:
        raise ValueError(f"advanced form is missing hidden {name!r}")
    return value


def _table(form: FilterForm, field: str) -> dict[int, str]:
    options = form.select_lists.get(field)
    if options is None:
        raise ValueError(f"advanced form is missing select {field!r}")
    table: dict[int, str] = {}
    for option in options:
        if not option.value:
            continue
        table[_option_int(option, field)] = option.label
    if not table:
        raise ValueError(f"advanced form select {field!r} has no ID values")
    return table


def _option_int(option: FormOption, field: str) -> int:
    try:
        return int(option.value)
    except ValueError as error:
        raise ValueError(
            f"{field!r} option {option.label!r} has non-integer value {option.value!r}"
        ) from error


def _emit_tuple(name: str, values: tuple[int, ...]) -> str:
    return f"{name}: tuple[int, ...] = {values!r}\n\n"


def _emit_dict(name: str, values: Mapping[int, str]) -> str:
    lines = [f"{name}: dict[int, str] = {{\n"]
    for key in sorted(values):
        lines.append(f"    {key}: {_string_literal(values[key])},\n")
    lines.append("}\n\n")
    return "".join(lines)


def _emit_nested_dict(name: str, values: Mapping[int, Mapping[int, str]]) -> str:
    lines = [f"{name}: dict[int, dict[int, str]] = {{\n"]
    for class_id in CLASS_IDS:
        lines.append(f"    {class_id}: {{\n")
        for item_id in sorted(values[class_id]):
            lines.append(f"        {item_id}: {_string_literal(values[class_id][item_id])},\n")
        lines.append("    },\n")
    lines.append("}\n\n")
    return "".join(lines)


def _string_literal(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


async def _fetch_html_by_class(output_dir: Path | None) -> dict[int, str]:
    pages = await fetch_lookup_pages(ids_requests(), save_pages=output_dir, budget=120)
    return {int(class_id): html for class_id, html in pages.items()}


def _read_html_by_class(input_dir: Path) -> dict[int, str]:
    pages = read_lookup_pages(ids_requests(), input_pages=input_dir)
    return {int(class_id): html for class_id, html in pages.items()}


async def _main_async(args: argparse.Namespace) -> None:
    html_by_class = (
        _read_html_by_class(args.input_pages)
        if args.input_pages is not None
        else await _fetch_html_by_class(args.save_pages)
    )
    generated_on = args.generated_on or date.today()
    text = module_text_from_html_by_class(html_by_class, generated_on=generated_on)
    args.output.write_text(text, encoding="utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate crickey's built-in Statsguru ID tables.")
    parser.add_argument("--output", type=Path, default=Path("src/crickey/id_tables.py"))
    parser.add_argument("--save-pages", type=Path, default=Path(".local/pages"))
    parser.add_argument(
        "--input-pages",
        type=Path,
        help=(
            "Read previously saved gen_ids_class_*_advanced_batting.html pages instead of fetching."
        ),
    )
    parser.add_argument(
        "--generated-on",
        type=date.fromisoformat,
        help="Data-capture date to write into the generated module, as YYYY-MM-DD.",
    )
    args = parser.parse_args()
    asyncio.run(_main_async(args))


if __name__ == "__main__":
    main()
