from __future__ import annotations

# Generated from local Statsguru advanced form snapshots for issue #6.
# Regenerate with parse_filter_form if the committed snapshots are refreshed.

TYPE_FIELD_KINDS = {
    "aggregate": {
        "continent": "select",
        "final_type": "select",
        "floodlit": "checkbox",
        "ground": "select",
        "host": "select",
        "qualquickpick": "select",
        "search_captain": "text",
        "search_player": "text",
        "season": "select",
        "series": "select",
        "spanquickpick": "select",
        "team": "select",
        "tournament_type": "checkbox",
        "trophy": "select",
    },
    "allround": {
        "agemax1": "text",
        "agemin1": "text",
        "agequickpick": "select",
        "ballsmax1": "text",
        "ballsmin1": "text",
        "ballsquickpick": "select",
        "batting_fielding_first": "radio",
        "batting_hand": "checkbox",
        "batting_positionmax1": "text",
        "batting_positionmin1": "text",
        "batting_positionquickpick": "select",
        "bowling_hand": "checkbox",
        "bowling_pacespin": "checkbox",
        "bowling_positionmax1": "text",
        "bowling_positionmin1": "text",
        "bowling_positionquickpick": "select",
        "captain": "radio",
        "caughtmax1": "text",
        "caughtmin1": "text",
        "caughtquickpick": "select",
        "concededmax1": "text",
        "concededmin1": "text",
        "concededquickpick": "select",
        "continent": "select",
        "debut_or_last": "checkbox",
        "dismissal": "select",
        "final_type": "select",
        "floodlit": "checkbox",
        "ground": "select",
        "home_or_away": "checkbox",
        "host": "select",
        "innings_number": "checkbox",
        "keeper": "radio",
        "opposition": "select",
        "outs": "radio",
        "qualquickpick": "select",
        "result": "checkbox",
        "runsmax1": "text",
        "runsmin1": "text",
        "runsquickpick": "select",
        "search_captain": "text",
        "search_player": "text",
        "season": "select",
        "series": "select",
        "spanquickpick": "select",
        "stumpedmax1": "text",
        "stumpedmin1": "text",
        "stumpedquickpick": "select",
        "team": "select",
        "toss": "radio",
        "tournament_type": "checkbox",
        "trophy": "select",
        "wicketsmax1": "text",
        "wicketsmin1": "text",
        "wicketsquickpick": "select",
    },
    "batting": {
        "agemax1": "text",
        "agemin1": "text",
        "agequickpick": "select",
        "batting_fielding_first": "radio",
        "batting_hand": "checkbox",
        "batting_positionmax1": "text",
        "batting_positionmin1": "text",
        "batting_positionquickpick": "select",
        "captain": "radio",
        "continent": "select",
        "debut_or_last": "checkbox",
        "dismissal": "select",
        "final_type": "select",
        "floodlit": "checkbox",
        "ground": "select",
        "home_or_away": "checkbox",
        "host": "select",
        "innings_number": "checkbox",
        "keeper": "radio",
        "opposition": "select",
        "outs": "radio",
        "qualquickpick": "select",
        "result": "checkbox",
        "runsmax1": "text",
        "runsmin1": "text",
        "runsquickpick": "select",
        "search_captain": "text",
        "search_player": "text",
        "season": "select",
        "series": "select",
        "spanquickpick": "select",
        "team": "select",
        "toss": "radio",
        "tournament_type": "checkbox",
        "trophy": "select",
    },
    "bowling": {
        "agemax1": "text",
        "agemin1": "text",
        "agequickpick": "select",
        "ballsmax1": "text",
        "ballsmin1": "text",
        "ballsquickpick": "select",
        "batting_fielding_first": "radio",
        "bowling_hand": "checkbox",
        "bowling_pacespin": "checkbox",
        "bowling_positionmax1": "text",
        "bowling_positionmin1": "text",
        "bowling_positionquickpick": "select",
        "captain": "radio",
        "concededmax1": "text",
        "concededmin1": "text",
        "concededquickpick": "select",
        "continent": "select",
        "debut_or_last": "checkbox",
        "final_type": "select",
        "floodlit": "checkbox",
        "ground": "select",
        "home_or_away": "checkbox",
        "host": "select",
        "innings_number": "checkbox",
        "keeper": "radio",
        "opposition": "select",
        "qualquickpick": "select",
        "result": "checkbox",
        "search_captain": "text",
        "search_player": "text",
        "season": "select",
        "series": "select",
        "spanquickpick": "select",
        "team": "select",
        "toss": "radio",
        "tournament_type": "checkbox",
        "trophy": "select",
        "wicketsmax1": "text",
        "wicketsmin1": "text",
        "wicketsquickpick": "select",
    },
    "fielding": {
        "agemax1": "text",
        "agemin1": "text",
        "agequickpick": "select",
        "batting_fielding_first": "radio",
        "captain": "radio",
        "caughtmax1": "text",
        "caughtmin1": "text",
        "caughtquickpick": "select",
        "continent": "select",
        "debut_or_last": "checkbox",
        "final_type": "select",
        "floodlit": "checkbox",
        "ground": "select",
        "home_or_away": "checkbox",
        "host": "select",
        "innings_number": "checkbox",
        "keeper": "radio",
        "opposition": "select",
        "qualquickpick": "select",
        "result": "checkbox",
        "search_captain": "text",
        "search_player": "text",
        "season": "select",
        "series": "select",
        "spanquickpick": "select",
        "stumpedmax1": "text",
        "stumpedmin1": "text",
        "stumpedquickpick": "select",
        "team": "select",
        "toss": "radio",
        "tournament_type": "checkbox",
        "trophy": "select",
    },
    "fow": {
        "batting_fielding_first": "radio",
        "continent": "select",
        "final_type": "select",
        "floodlit": "checkbox",
        "fow_type": "select",
        "ground": "select",
        "home_or_away": "checkbox",
        "host": "select",
        "innings_number": "checkbox",
        "opposition": "select",
        "partnership_runsmax1": "text",
        "partnership_runsmin1": "text",
        "partnership_runsquickpick": "select",
        "partnership_wicketmax1": "text",
        "partnership_wicketmin1": "text",
        "partnership_wicketquickpick": "select",
        "qualquickpick": "select",
        "result": "checkbox",
        "search_captain": "text",
        "search_player": "text",
        "season": "select",
        "series": "select",
        "spanquickpick": "select",
        "team": "select",
        "toss": "radio",
        "tournament_type": "checkbox",
        "trophy": "select",
    },
    "team": {
        "ballsmax1": "text",
        "ballsmin1": "text",
        "ballsquickpick": "select",
        "batting_fielding_first": "radio",
        "continent": "select",
        "event": "select",
        "final_type": "select",
        "floodlit": "checkbox",
        "ground": "select",
        "home_or_away": "checkbox",
        "host": "select",
        "innings_number": "checkbox",
        "opposition": "select",
        "qualquickpick": "select",
        "result": "checkbox",
        "runsmax1": "text",
        "runsmin1": "text",
        "runsquickpick": "select",
        "search_captain": "text",
        "search_player": "text",
        "season": "select",
        "series": "select",
        "spanquickpick": "select",
        "team": "select",
        "team_view": "radio",
        "toss": "radio",
        "tournament_type": "checkbox",
        "trophy": "select",
        "wicketsmax1": "text",
        "wicketsmin1": "text",
        "wicketsquickpick": "select",
    },
}

MULTI_FIELDS = {
    "aggregate": ["floodlit", "tournament_type"],
    "allround": [
        "batting_hand",
        "bowling_hand",
        "bowling_pacespin",
        "debut_or_last",
        "floodlit",
        "home_or_away",
        "innings_number",
        "result",
        "tournament_type",
    ],
    "batting": [
        "batting_hand",
        "debut_or_last",
        "floodlit",
        "home_or_away",
        "innings_number",
        "result",
        "tournament_type",
    ],
    "bowling": [
        "bowling_hand",
        "bowling_pacespin",
        "debut_or_last",
        "floodlit",
        "home_or_away",
        "innings_number",
        "result",
        "tournament_type",
    ],
    "fielding": [
        "debut_or_last",
        "floodlit",
        "home_or_away",
        "innings_number",
        "result",
        "tournament_type",
    ],
    "fow": ["floodlit", "home_or_away", "innings_number", "result", "tournament_type"],
    "team": ["floodlit", "home_or_away", "innings_number", "result", "tournament_type"],
}

TYPE_VIEWS = {
    "aggregate": ["", "match", "results", "series", "ground", "host", "year", "season", "extras"],
    "allround": [
        "",
        "innings",
        "match",
        "results",
        "awards",
        "series",
        "ground",
        "host",
        "opposition",
        "year",
        "season",
    ],
    "batting": ["", "innings", "match", "series", "ground", "host", "opposition", "year", "season"],
    "bowling": ["", "innings", "match", "series", "ground", "host", "opposition", "year", "season"],
    "fielding": [
        "",
        "innings",
        "match",
        "series",
        "ground",
        "host",
        "opposition",
        "year",
        "season",
    ],
    "fow": ["", "innings", "match", "series", "ground", "host", "opposition", "year", "season"],
    "team": [
        "",
        "innings",
        "match",
        "results",
        "series",
        "ground",
        "host",
        "opposition",
        "year",
        "season",
        "extras",
        "extras_innings",
    ],
}

TYPE_GROUPBYS = {
    "aggregate": [],
    "allround": [
        "",
        "innings",
        "match",
        "series",
        "tour",
        "team",
        "opposition",
        "ground",
        "host",
        "continent",
        "year",
        "season",
        "decade",
        "overall",
    ],
    "batting": [
        "",
        "innings",
        "match",
        "series",
        "tour",
        "team",
        "opposition",
        "ground",
        "host",
        "continent",
        "year",
        "season",
        "decade",
        "overall",
    ],
    "bowling": [
        "",
        "innings",
        "match",
        "series",
        "tour",
        "team",
        "opposition",
        "ground",
        "host",
        "continent",
        "year",
        "season",
        "decade",
        "overall",
    ],
    "fielding": [
        "",
        "innings",
        "match",
        "series",
        "tour",
        "team",
        "opposition",
        "ground",
        "host",
        "continent",
        "year",
        "season",
        "decade",
        "overall",
    ],
    "fow": [
        "",
        "fow_wicket",
        "innings",
        "match",
        "series",
        "tour",
        "team",
        "opposition",
        "ground",
        "host",
        "continent",
        "year",
        "season",
        "decade",
        "overall",
    ],
    "team": [
        "",
        "players",
        "captains",
        "match",
        "series",
        "tour",
        "ground",
        "host",
        "continent",
        "year",
        "season",
        "decade",
        "overall",
    ],
}

QUAL_FIELDS = {
    "aggregate": {
        "": [
            "matches",
            "won",
            "tied",
            "drawn",
            "no_result",
            "percentage_won",
            "percentage_lost",
            "percentage_drawn",
            "percentage_tied",
            "percentage_no_result",
            "runs",
            "wickets",
            "balls",
            "team_average",
            "runs_per_over",
        ],
        "extras": [
            "matches",
            "extras",
            "byes",
            "legbyes",
            "wides",
            "noballs",
            "penalties",
            "runs",
            "percent_extras",
            "wickets",
            "balls",
        ],
        "ground": [
            "matches",
            "won",
            "tied",
            "drawn",
            "no_result",
            "percentage_won",
            "percentage_lost",
            "percentage_drawn",
            "percentage_tied",
            "percentage_no_result",
            "runs",
            "wickets",
            "balls",
            "team_average",
            "runs_per_over",
        ],
        "host": [
            "matches",
            "won",
            "tied",
            "drawn",
            "no_result",
            "percentage_won",
            "percentage_lost",
            "percentage_drawn",
            "percentage_tied",
            "percentage_no_result",
            "runs",
            "wickets",
            "balls",
            "team_average",
            "runs_per_over",
        ],
        "match": ["runs", "wickets", "balls", "team_average", "runs_per_over"],
        "opposition": [
            "matches",
            "won",
            "tied",
            "drawn",
            "no_result",
            "percentage_won",
            "percentage_lost",
            "percentage_drawn",
            "percentage_tied",
            "percentage_no_result",
            "runs",
            "wickets",
            "balls",
            "team_average",
            "runs_per_over",
        ],
        "results": [],
        "season": [
            "season",
            "matches",
            "won",
            "tied",
            "drawn",
            "no_result",
            "percentage_won",
            "percentage_lost",
            "percentage_drawn",
            "percentage_tied",
            "percentage_no_result",
            "runs",
            "wickets",
            "balls",
            "team_average",
            "runs_per_over",
        ],
        "series": [
            "matches",
            "won",
            "tied",
            "drawn",
            "no_result",
            "percentage_won",
            "percentage_lost",
            "percentage_drawn",
            "percentage_tied",
            "percentage_no_result",
            "runs",
            "wickets",
            "balls",
            "team_average",
            "runs_per_over",
        ],
        "year": [
            "year",
            "matches",
            "won",
            "tied",
            "drawn",
            "no_result",
            "percentage_won",
            "percentage_lost",
            "percentage_drawn",
            "percentage_tied",
            "percentage_no_result",
            "runs",
            "wickets",
            "balls",
            "team_average",
            "runs_per_over",
        ],
    },
    "allround": {
        "": [
            "matches",
            "innings",
            "notouts",
            "outs",
            "runs",
            "minutes",
            "batting_average",
            "balls_faced",
            "batting_strike_rate",
            "hundreds",
            "fifty_plus",
            "ducks",
            "fours",
            "sixes",
            "innings_bowled",
            "balls",
            "maidens",
            "conceded",
            "wickets",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "four_plus_wickets",
            "five_wickets",
            "ten_wickets",
            "matches_keeper",
            "matches_fielder",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "dismissals_per_inns",
            "allround_average",
        ],
        "awards": ["matches", "awards_match", "awards_series"],
        "awards_match": [
            "innings",
            "notouts",
            "outs",
            "runs",
            "minutes",
            "batting_average",
            "balls_faced",
            "batting_strike_rate",
            "hundreds",
            "fifty_plus",
            "ducks",
            "fours",
            "sixes",
            "innings_bowled",
            "balls",
            "maidens",
            "conceded",
            "wickets",
            "economy_rate",
            "bowling_average",
            "bowling_strike_rate",
            "four_wickets",
            "four_plus_wickets",
            "five_wickets",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "dismissals_per_inns",
        ],
        "awards_series": [
            "matches",
            "innings",
            "notouts",
            "outs",
            "runs",
            "minutes",
            "batting_average",
            "balls_faced",
            "batting_strike_rate",
            "hundreds",
            "fifty_plus",
            "ducks",
            "fours",
            "sixes",
            "innings_bowled",
            "balls",
            "maidens",
            "conceded",
            "wickets",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "four_plus_wickets",
            "five_wickets",
            "ten_wickets",
            "matches_keeper",
            "matches_fielder",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "dismissals_per_inns",
            "allround_average",
        ],
        "cumulative": [
            "batting_average",
            "batting_strike_rate",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "dismissals_per_inns",
        ],
        "ground": [
            "matches",
            "innings",
            "notouts",
            "outs",
            "runs",
            "minutes",
            "batting_average",
            "balls_faced",
            "batting_strike_rate",
            "hundreds",
            "fifty_plus",
            "ducks",
            "fours",
            "sixes",
            "innings_bowled",
            "balls",
            "maidens",
            "conceded",
            "wickets",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "four_plus_wickets",
            "five_wickets",
            "ten_wickets",
            "matches_keeper",
            "matches_fielder",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "dismissals_per_inns",
            "allround_average",
        ],
        "host": [
            "matches",
            "innings",
            "notouts",
            "outs",
            "runs",
            "minutes",
            "batting_average",
            "balls_faced",
            "batting_strike_rate",
            "hundreds",
            "fifty_plus",
            "ducks",
            "fours",
            "sixes",
            "innings_bowled",
            "balls",
            "maidens",
            "conceded",
            "wickets",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "four_plus_wickets",
            "five_wickets",
            "ten_wickets",
            "matches_keeper",
            "matches_fielder",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "dismissals_per_inns",
            "allround_average",
        ],
        "innings": [
            "innings_number",
            "batted_score",
            "minutes",
            "balls_faced",
            "fours",
            "sixes",
            "batting_strike_rate",
            "bowled_balls",
            "maidens",
            "conceded",
            "wickets",
            "economy_rate",
            "bowling_average",
            "bowling_strike_rate",
            "fielded_dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
        ],
        "match": [
            "innings",
            "notouts",
            "outs",
            "runs",
            "minutes",
            "batting_average",
            "balls_faced",
            "batting_strike_rate",
            "hundreds",
            "fifty_plus",
            "ducks",
            "fours",
            "sixes",
            "innings_bowled",
            "balls",
            "maidens",
            "conceded",
            "wickets",
            "economy_rate",
            "bowling_average",
            "bowling_strike_rate",
            "four_wickets",
            "four_plus_wickets",
            "five_wickets",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "dismissals_per_inns",
        ],
        "opposition": [
            "matches",
            "innings",
            "notouts",
            "outs",
            "runs",
            "minutes",
            "batting_average",
            "balls_faced",
            "batting_strike_rate",
            "hundreds",
            "fifty_plus",
            "ducks",
            "fours",
            "sixes",
            "innings_bowled",
            "balls",
            "maidens",
            "conceded",
            "wickets",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "four_plus_wickets",
            "five_wickets",
            "ten_wickets",
            "matches_keeper",
            "matches_fielder",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "dismissals_per_inns",
            "allround_average",
        ],
        "results": [],
        "reverse_cumulative": [
            "batting_average",
            "batting_strike_rate",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "dismissals_per_inns",
        ],
        "season": [
            "season",
            "matches",
            "innings",
            "notouts",
            "outs",
            "runs",
            "minutes",
            "batting_average",
            "balls_faced",
            "batting_strike_rate",
            "hundreds",
            "fifty_plus",
            "ducks",
            "fours",
            "sixes",
            "innings_bowled",
            "balls",
            "maidens",
            "conceded",
            "wickets",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "four_plus_wickets",
            "five_wickets",
            "ten_wickets",
            "matches_keeper",
            "matches_fielder",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "dismissals_per_inns",
            "allround_average",
        ],
        "series": [
            "matches",
            "innings",
            "notouts",
            "outs",
            "runs",
            "minutes",
            "batting_average",
            "balls_faced",
            "batting_strike_rate",
            "hundreds",
            "fifty_plus",
            "ducks",
            "fours",
            "sixes",
            "innings_bowled",
            "balls",
            "maidens",
            "conceded",
            "wickets",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "four_plus_wickets",
            "five_wickets",
            "ten_wickets",
            "matches_keeper",
            "matches_fielder",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "dismissals_per_inns",
            "allround_average",
        ],
        "year": [
            "year",
            "matches",
            "innings",
            "notouts",
            "outs",
            "runs",
            "minutes",
            "batting_average",
            "balls_faced",
            "batting_strike_rate",
            "hundreds",
            "fifty_plus",
            "ducks",
            "fours",
            "sixes",
            "innings_bowled",
            "balls",
            "maidens",
            "conceded",
            "wickets",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "four_plus_wickets",
            "five_wickets",
            "ten_wickets",
            "matches_keeper",
            "matches_fielder",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "dismissals_per_inns",
            "allround_average",
        ],
    },
    "batting": {
        "": [
            "matches",
            "innings",
            "notouts",
            "outs",
            "runs",
            "minutes",
            "balls_faced",
            "batting_average",
            "batting_strike_rate",
            "hundreds",
            "fifty_plus",
            "ducks",
            "fours",
            "sixes",
        ],
        "bowler_summary": [
            "dis_matches",
            "dis_dismissals",
            "dis_bowled",
            "dis_caught_fielder",
            "dis_caught_keeper",
            "dis_stumped",
            "dis_lbw",
            "dis_hit_wicket",
            "dis_matches_per_dismissal",
            "dis_average",
            "dis_ducks",
        ],
        "cumulative": ["batting_average", "batting_strike_rate"],
        "dismissal_list": ["dis_runs", "dis_innings_number"],
        "dismissal_summary": [
            "dis_dismissals",
            "dis_bowled",
            "dis_caught_fielder",
            "dis_caught_keeper",
            "dis_stumped",
            "dis_lbw",
            "dis_hit_wicket",
            "dis_run_out",
            "dis_other",
            "dis_not_out",
            "dis_average",
            "dis_ducks",
        ],
        "fielder_summary": [
            "dis_matches",
            "dis_dismissals",
            "dis_caught_fielder",
            "dis_caught_keeper",
            "dis_stumped",
            "dis_matches_per_dismissal",
            "dis_average",
            "dis_ducks",
        ],
        "fow_list": ["start", "fow_wicket", "fow_score", "fow_in", "fow_out", "fow_innings_number"],
        "fow_summary": [
            "start",
            "fow_innings",
            "fow_notouts",
            "fow_outs",
            "fow_runs",
            "fow_average",
            "fow_hundreds",
            "fow_fifty_plus",
        ],
        "ground": [
            "matches",
            "innings",
            "notouts",
            "outs",
            "runs",
            "minutes",
            "balls_faced",
            "batting_average",
            "batting_strike_rate",
            "hundreds",
            "fifty_plus",
            "ducks",
            "fours",
            "sixes",
        ],
        "host": [
            "matches",
            "innings",
            "notouts",
            "outs",
            "runs",
            "minutes",
            "balls_faced",
            "batting_average",
            "batting_strike_rate",
            "hundreds",
            "fifty_plus",
            "ducks",
            "fours",
            "sixes",
        ],
        "innings": [
            "batted_score",
            "minutes",
            "balls_faced",
            "fours",
            "sixes",
            "batting_strike_rate",
        ],
        "match": [
            "runs",
            "minutes",
            "balls_faced",
            "fours",
            "sixes",
            "batting_strike_rate",
            "innings",
            "notouts",
            "outs",
            "high_score",
            "batting_average",
            "hundreds",
            "fifty_plus",
            "ducks",
        ],
        "opposition": [
            "matches",
            "innings",
            "notouts",
            "outs",
            "runs",
            "minutes",
            "balls_faced",
            "batting_average",
            "batting_strike_rate",
            "hundreds",
            "fifty_plus",
            "ducks",
            "fours",
            "sixes",
        ],
        "reverse_cumulative": ["batting_average", "batting_strike_rate"],
        "season": [
            "season",
            "matches",
            "innings",
            "notouts",
            "outs",
            "runs",
            "minutes",
            "balls_faced",
            "batting_average",
            "batting_strike_rate",
            "hundreds",
            "fifty_plus",
            "ducks",
            "fours",
            "sixes",
        ],
        "series": [
            "matches",
            "innings",
            "notouts",
            "outs",
            "runs",
            "minutes",
            "balls_faced",
            "batting_average",
            "batting_strike_rate",
            "hundreds",
            "fifty_plus",
            "ducks",
            "fours",
            "sixes",
        ],
        "year": [
            "year",
            "matches",
            "innings",
            "notouts",
            "outs",
            "runs",
            "minutes",
            "balls_faced",
            "batting_average",
            "batting_strike_rate",
            "hundreds",
            "fifty_plus",
            "ducks",
            "fours",
            "sixes",
        ],
    },
    "bowling": {
        "": [
            "matches",
            "innings_bowled",
            "balls",
            "overs",
            "maidens",
            "conceded",
            "wickets",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "four_plus_wickets",
            "five_wickets",
            "ten_wickets",
        ],
        "batsman_summary": [
            "dis_matches",
            "dis_dismissals",
            "dis_bowled",
            "dis_caught_fielder",
            "dis_caught_keeper",
            "dis_stumped",
            "dis_lbw",
            "dis_hit_wicket",
            "dis_matches_per_dismissal",
            "dis_average",
            "dis_ducks",
        ],
        "cumulative": ["bowling_average", "economy_rate", "bowling_strike_rate"],
        "dismissal_list": ["dis_runs", "dis_innings_number"],
        "dismissal_summary": [
            "dis_dismissals",
            "dis_bowled",
            "dis_caught_fielder",
            "dis_caught_keeper",
            "dis_stumped",
            "dis_lbw",
            "dis_hit_wicket",
            "dis_average",
            "dis_ducks",
        ],
        "fielder_summary": [
            "dis_matches",
            "dis_dismissals",
            "dis_caught_fielder",
            "dis_caught_keeper",
            "dis_stumped",
            "dis_matches_per_dismissal",
            "dis_average",
            "dis_ducks",
        ],
        "ground": [
            "matches",
            "innings_bowled",
            "balls",
            "overs",
            "maidens",
            "conceded",
            "wickets",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "four_plus_wickets",
            "five_wickets",
            "ten_wickets",
        ],
        "host": [
            "matches",
            "innings_bowled",
            "balls",
            "overs",
            "maidens",
            "conceded",
            "wickets",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "four_plus_wickets",
            "five_wickets",
            "ten_wickets",
        ],
        "innings": [
            "overs",
            "maidens",
            "conceded",
            "wickets",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "bowling_position",
        ],
        "match": [
            "innings_bowled",
            "overs",
            "maidens",
            "conceded",
            "wickets",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "four_plus_wickets",
            "five_wickets",
            "ten_wickets",
        ],
        "opposition": [
            "matches",
            "innings_bowled",
            "balls",
            "overs",
            "maidens",
            "conceded",
            "wickets",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "four_plus_wickets",
            "five_wickets",
            "ten_wickets",
        ],
        "reverse_cumulative": ["bowling_average", "economy_rate", "bowling_strike_rate"],
        "season": [
            "season",
            "matches",
            "innings_bowled",
            "balls",
            "overs",
            "maidens",
            "conceded",
            "wickets",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "four_plus_wickets",
            "five_wickets",
            "ten_wickets",
        ],
        "series": [
            "matches",
            "innings_bowled",
            "balls",
            "overs",
            "maidens",
            "conceded",
            "wickets",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "four_plus_wickets",
            "five_wickets",
            "ten_wickets",
        ],
        "year": [
            "year",
            "matches",
            "innings_bowled",
            "balls",
            "overs",
            "maidens",
            "conceded",
            "wickets",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "four_plus_wickets",
            "five_wickets",
            "ten_wickets",
        ],
    },
    "fielding": {
        "": [
            "matches",
            "matches_keeper",
            "matches_fielder",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "dismissals_per_inns",
        ],
        "batsman_summary": [
            "dis_matches",
            "dis_dismissals",
            "dis_caught_fielder",
            "dis_caught_keeper",
            "dis_stumped",
            "dis_matches_per_dismissal",
            "dis_average",
            "dis_ducks",
        ],
        "bowler_summary": [
            "dis_matches",
            "dis_dismissals",
            "dis_caught_fielder",
            "dis_caught_keeper",
            "dis_stumped",
            "dis_matches_per_dismissal",
            "dis_average",
            "dis_ducks",
        ],
        "cumulative": ["dismissals_per_inns"],
        "dismissal_list": ["dis_runs", "dis_innings_number"],
        "dismissal_summary": [
            "dis_dismissals",
            "dis_caught_fielder",
            "dis_caught_keeper",
            "dis_stumped",
            "dis_average",
            "dis_ducks",
        ],
        "ground": [
            "matches",
            "matches_keeper",
            "matches_fielder",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "dismissals_per_inns",
        ],
        "host": [
            "matches",
            "matches_keeper",
            "matches_fielder",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "dismissals_per_inns",
        ],
        "innings": ["fielded_dismissals", "caught", "stumped", "caught_keeper", "caught_fielder"],
        "match": [
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "dismissals_per_inns",
        ],
        "opposition": [
            "matches",
            "matches_keeper",
            "matches_fielder",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "dismissals_per_inns",
        ],
        "reverse_cumulative": ["dismissals_per_inns"],
        "season": [
            "season",
            "matches",
            "matches_keeper",
            "matches_fielder",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "dismissals_per_inns",
        ],
        "series": [
            "matches",
            "matches_keeper",
            "matches_fielder",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "dismissals_per_inns",
        ],
        "year": [
            "year",
            "matches",
            "matches_keeper",
            "matches_fielder",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "dismissals_per_inns",
        ],
    },
    "fow": {
        "": [
            "fow_innings",
            "fow_notouts",
            "fow_outs",
            "fow_runs",
            "fow_average",
            "fow_balls_faced",
            "fow_run_rate",
            "fow_hundreds",
            "fow_fifty_plus",
        ],
        "ground": [
            "fow_innings",
            "fow_notouts",
            "fow_outs",
            "fow_runs",
            "fow_average",
            "fow_balls_faced",
            "fow_run_rate",
            "fow_hundreds",
            "fow_fifty_plus",
        ],
        "host": [
            "fow_innings",
            "fow_notouts",
            "fow_outs",
            "fow_runs",
            "fow_average",
            "fow_balls_faced",
            "fow_run_rate",
            "fow_hundreds",
            "fow_fifty_plus",
        ],
        "innings": [
            "fow_wicket",
            "fow_score",
            "fow_balls_faced",
            "fow_run_rate",
            "fow_in",
            "fow_out",
            "fow_innings_number",
        ],
        "match": [
            "fow_innings",
            "fow_notouts",
            "fow_outs",
            "fow_runs",
            "fow_average",
            "fow_balls_faced",
            "fow_run_rate",
            "fow_hundreds",
            "fow_fifty_plus",
        ],
        "opposition": [
            "fow_innings",
            "fow_notouts",
            "fow_outs",
            "fow_runs",
            "fow_average",
            "fow_balls_faced",
            "fow_run_rate",
            "fow_hundreds",
            "fow_fifty_plus",
        ],
        "season": [
            "season",
            "fow_innings",
            "fow_notouts",
            "fow_outs",
            "fow_runs",
            "fow_average",
            "fow_balls_faced",
            "fow_run_rate",
            "fow_hundreds",
            "fow_fifty_plus",
        ],
        "series": [
            "fow_innings",
            "fow_notouts",
            "fow_outs",
            "fow_runs",
            "fow_average",
            "fow_balls_faced",
            "fow_run_rate",
            "fow_hundreds",
            "fow_fifty_plus",
        ],
        "year": [
            "year",
            "fow_innings",
            "fow_notouts",
            "fow_outs",
            "fow_runs",
            "fow_average",
            "fow_balls_faced",
            "fow_run_rate",
            "fow_hundreds",
            "fow_fifty_plus",
        ],
    },
    "team": {
        "": [
            "matches",
            "won",
            "lost",
            "tied",
            "drawn",
            "no_result",
            "win_loss_ratio",
            "percentage_won",
            "percentage_lost",
            "percentage_drawn",
            "percentage_tied",
            "percentage_no_result",
            "runs",
            "wickets",
            "balls",
            "team_average",
            "runs_per_over",
            "team_innings",
            "team_high_score",
            "team_low_score",
        ],
        "cumulative": [
            "win_loss_ratio",
            "percentage_won",
            "percentage_lost",
            "percentage_drawn",
            "percentage_tied",
            "percentage_no_result",
            "team_average",
            "runs_per_over",
        ],
        "extras": [
            "matches",
            "extras",
            "byes",
            "legbyes",
            "wides",
            "noballs",
            "penalties",
            "runs",
            "percent_extras",
            "wickets",
            "balls",
        ],
        "extras_innings": [
            "extras",
            "byes",
            "legbyes",
            "wides",
            "noballs",
            "penalties",
            "team_score",
            "percent_extras",
            "team_wickets",
            "team_overs",
            "innings_number",
        ],
        "ground": [
            "matches",
            "won",
            "lost",
            "tied",
            "drawn",
            "no_result",
            "win_loss_ratio",
            "percentage_won",
            "percentage_lost",
            "percentage_drawn",
            "percentage_tied",
            "percentage_no_result",
            "runs",
            "wickets",
            "balls",
            "team_average",
            "runs_per_over",
            "team_innings",
            "team_high_score",
            "team_low_score",
        ],
        "ground_results": ["amount", "amount_balls"],
        "host": [
            "matches",
            "won",
            "lost",
            "tied",
            "drawn",
            "no_result",
            "win_loss_ratio",
            "percentage_won",
            "percentage_lost",
            "percentage_drawn",
            "percentage_tied",
            "percentage_no_result",
            "runs",
            "wickets",
            "balls",
            "team_average",
            "runs_per_over",
            "team_innings",
            "team_high_score",
            "team_low_score",
        ],
        "innings": [
            "team_score",
            "team_wickets",
            "team_overs",
            "target",
            "lead",
            "team_average",
            "runs_per_over",
            "innings_number",
        ],
        "match": ["runs", "wickets", "balls", "team_average", "runs_per_over"],
        "opposition": [
            "matches",
            "won",
            "lost",
            "tied",
            "drawn",
            "no_result",
            "win_loss_ratio",
            "percentage_won",
            "percentage_lost",
            "percentage_drawn",
            "percentage_tied",
            "percentage_no_result",
            "runs",
            "wickets",
            "balls",
            "team_average",
            "runs_per_over",
            "team_innings",
            "team_high_score",
            "team_low_score",
        ],
        "results": [],
        "reverse_cumulative": [
            "win_loss_ratio",
            "percentage_won",
            "percentage_lost",
            "percentage_drawn",
            "percentage_tied",
            "percentage_no_result",
            "team_average",
            "runs_per_over",
        ],
        "season": [
            "season",
            "matches",
            "won",
            "lost",
            "tied",
            "drawn",
            "no_result",
            "win_loss_ratio",
            "percentage_won",
            "percentage_lost",
            "percentage_drawn",
            "percentage_tied",
            "percentage_no_result",
            "runs",
            "wickets",
            "balls",
            "team_average",
            "runs_per_over",
            "team_innings",
            "team_high_score",
            "team_low_score",
        ],
        "series": [
            "matches",
            "won",
            "lost",
            "tied",
            "drawn",
            "no_result",
            "win_loss_ratio",
            "percentage_won",
            "percentage_lost",
            "percentage_drawn",
            "percentage_tied",
            "percentage_no_result",
            "runs",
            "wickets",
            "balls",
            "team_average",
            "runs_per_over",
            "team_innings",
            "team_high_score",
            "team_low_score",
        ],
        "toss_results": ["result"],
        "year": [
            "year",
            "matches",
            "won",
            "lost",
            "tied",
            "drawn",
            "no_result",
            "win_loss_ratio",
            "percentage_won",
            "percentage_lost",
            "percentage_drawn",
            "percentage_tied",
            "percentage_no_result",
            "runs",
            "wickets",
            "balls",
            "team_average",
            "runs_per_over",
            "team_innings",
            "team_high_score",
            "team_low_score",
        ],
    },
}

SORT_FIELDS = {
    "aggregate": {
        "": [
            "start",
            "matches",
            "won",
            "tied",
            "drawn",
            "no_result",
            "percentage_won",
            "percentage_lost",
            "percentage_drawn",
            "percentage_tied",
            "percentage_no_result",
            "runs",
            "wickets",
            "balls",
            "team_average",
            "runs_per_over",
        ],
        "extras": [
            "start",
            "matches",
            "extras",
            "byes",
            "legbyes",
            "wides",
            "noballs",
            "penalties",
            "runs",
            "percent_extras",
            "wickets",
            "balls",
        ],
        "ground": [
            "start",
            "matches",
            "won",
            "tied",
            "drawn",
            "no_result",
            "percentage_won",
            "percentage_lost",
            "percentage_drawn",
            "percentage_tied",
            "percentage_no_result",
            "runs",
            "wickets",
            "balls",
            "team_average",
            "runs_per_over",
        ],
        "host": [
            "start",
            "matches",
            "won",
            "tied",
            "drawn",
            "no_result",
            "percentage_won",
            "percentage_lost",
            "percentage_drawn",
            "percentage_tied",
            "percentage_no_result",
            "runs",
            "wickets",
            "balls",
            "team_average",
            "runs_per_over",
        ],
        "match": ["start", "runs", "wickets", "balls", "team_average", "runs_per_over"],
        "opposition": [
            "start",
            "matches",
            "won",
            "tied",
            "drawn",
            "no_result",
            "percentage_won",
            "percentage_lost",
            "percentage_drawn",
            "percentage_tied",
            "percentage_no_result",
            "runs",
            "wickets",
            "balls",
            "team_average",
            "runs_per_over",
        ],
        "results": ["start", "winner", "result", "amount", "amount_balls"],
        "season": [
            "season",
            "matches",
            "won",
            "tied",
            "drawn",
            "no_result",
            "percentage_won",
            "percentage_lost",
            "percentage_drawn",
            "percentage_tied",
            "percentage_no_result",
            "runs",
            "wickets",
            "balls",
            "team_average",
            "runs_per_over",
        ],
        "series": [
            "start",
            "matches",
            "won",
            "tied",
            "drawn",
            "no_result",
            "percentage_won",
            "percentage_lost",
            "percentage_drawn",
            "percentage_tied",
            "percentage_no_result",
            "runs",
            "wickets",
            "balls",
            "team_average",
            "runs_per_over",
        ],
        "year": [
            "year",
            "matches",
            "won",
            "tied",
            "drawn",
            "no_result",
            "percentage_won",
            "percentage_lost",
            "percentage_drawn",
            "percentage_tied",
            "percentage_no_result",
            "runs",
            "wickets",
            "balls",
            "team_average",
            "runs_per_over",
        ],
    },
    "allround": {
        "": [
            "player",
            "start",
            "matches",
            "innings",
            "notouts",
            "outs",
            "runs",
            "minutes",
            "high_score",
            "batting_average",
            "balls_faced",
            "batting_strike_rate",
            "hundreds",
            "fifty_plus",
            "ducks",
            "fours",
            "sixes",
            "innings_bowled",
            "balls",
            "maidens",
            "conceded",
            "wickets",
            "bbi",
            "bbm",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "four_plus_wickets",
            "five_wickets",
            "ten_wickets",
            "matches_keeper",
            "matches_fielder",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "max_dismissals",
            "dismissals_per_inns",
            "allround_average",
        ],
        "awards": ["player", "start", "matches", "awards_match", "awards_series"],
        "awards_match": [
            "start",
            "batting_score1",
            "batting_score2",
            "innings",
            "notouts",
            "outs",
            "runs",
            "minutes",
            "high_score",
            "batting_average",
            "balls_faced",
            "batting_strike_rate",
            "hundreds",
            "fifty_plus",
            "ducks",
            "fours",
            "sixes",
            "innings_bowled",
            "balls",
            "maidens",
            "conceded",
            "wickets",
            "bbi",
            "economy_rate",
            "bowling_average",
            "bowling_strike_rate",
            "four_wickets",
            "four_plus_wickets",
            "five_wickets",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "max_dismissals",
            "dismissals_per_inns",
        ],
        "awards_series": [
            "player",
            "start",
            "matches",
            "innings",
            "notouts",
            "outs",
            "runs",
            "minutes",
            "high_score",
            "batting_average",
            "balls_faced",
            "batting_strike_rate",
            "hundreds",
            "fifty_plus",
            "ducks",
            "fours",
            "sixes",
            "innings_bowled",
            "balls",
            "maidens",
            "conceded",
            "wickets",
            "bbi",
            "bbm",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "four_plus_wickets",
            "five_wickets",
            "ten_wickets",
            "matches_keeper",
            "matches_fielder",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "max_dismissals",
            "dismissals_per_inns",
            "allround_average",
        ],
        "cumulative": [
            "start",
            "batting_average",
            "batting_strike_rate",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "dismissals_per_inns",
        ],
        "ground": [
            "player",
            "start",
            "matches",
            "innings",
            "notouts",
            "outs",
            "runs",
            "minutes",
            "high_score",
            "batting_average",
            "balls_faced",
            "batting_strike_rate",
            "hundreds",
            "fifty_plus",
            "ducks",
            "fours",
            "sixes",
            "innings_bowled",
            "balls",
            "maidens",
            "conceded",
            "wickets",
            "bbi",
            "bbm",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "four_plus_wickets",
            "five_wickets",
            "ten_wickets",
            "matches_keeper",
            "matches_fielder",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "max_dismissals",
            "dismissals_per_inns",
            "allround_average",
        ],
        "host": [
            "player",
            "start",
            "matches",
            "innings",
            "notouts",
            "outs",
            "runs",
            "minutes",
            "high_score",
            "batting_average",
            "balls_faced",
            "batting_strike_rate",
            "hundreds",
            "fifty_plus",
            "ducks",
            "fours",
            "sixes",
            "innings_bowled",
            "balls",
            "maidens",
            "conceded",
            "wickets",
            "bbi",
            "bbm",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "four_plus_wickets",
            "five_wickets",
            "ten_wickets",
            "matches_keeper",
            "matches_fielder",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "max_dismissals",
            "dismissals_per_inns",
            "allround_average",
        ],
        "innings": [
            "player",
            "start",
            "age",
            "innings_number",
            "batted_score",
            "minutes",
            "balls_faced",
            "fours",
            "sixes",
            "batting_strike_rate",
            "bowled_balls",
            "maidens",
            "conceded",
            "wickets",
            "economy_rate",
            "bowling_average",
            "bowling_strike_rate",
            "fielded_dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
        ],
        "match": [
            "player",
            "start",
            "age",
            "batting_score1",
            "batting_score2",
            "innings",
            "notouts",
            "outs",
            "runs",
            "minutes",
            "high_score",
            "batting_average",
            "balls_faced",
            "batting_strike_rate",
            "hundreds",
            "fifty_plus",
            "ducks",
            "fours",
            "sixes",
            "innings_bowled",
            "balls",
            "maidens",
            "conceded",
            "wickets",
            "bbi",
            "economy_rate",
            "bowling_average",
            "bowling_strike_rate",
            "four_wickets",
            "four_plus_wickets",
            "five_wickets",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "max_dismissals",
            "dismissals_per_inns",
        ],
        "opposition": [
            "player",
            "start",
            "matches",
            "innings",
            "notouts",
            "outs",
            "runs",
            "minutes",
            "high_score",
            "batting_average",
            "balls_faced",
            "batting_strike_rate",
            "hundreds",
            "fifty_plus",
            "ducks",
            "fours",
            "sixes",
            "innings_bowled",
            "balls",
            "maidens",
            "conceded",
            "wickets",
            "bbi",
            "bbm",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "four_plus_wickets",
            "five_wickets",
            "ten_wickets",
            "matches_keeper",
            "matches_fielder",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "max_dismissals",
            "dismissals_per_inns",
            "allround_average",
        ],
        "results": [
            "player",
            "start",
            "result",
            "amount",
            "amount_balls",
            "toss",
            "batting_fielding_first",
        ],
        "reverse_cumulative": [
            "start",
            "batting_average",
            "batting_strike_rate",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "dismissals_per_inns",
        ],
        "season": [
            "season",
            "player",
            "matches",
            "innings",
            "notouts",
            "outs",
            "runs",
            "minutes",
            "high_score",
            "batting_average",
            "balls_faced",
            "batting_strike_rate",
            "hundreds",
            "fifty_plus",
            "ducks",
            "fours",
            "sixes",
            "innings_bowled",
            "balls",
            "maidens",
            "conceded",
            "wickets",
            "bbi",
            "bbm",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "four_plus_wickets",
            "five_wickets",
            "ten_wickets",
            "matches_keeper",
            "matches_fielder",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "max_dismissals",
            "dismissals_per_inns",
            "allround_average",
        ],
        "series": [
            "player",
            "start",
            "matches",
            "innings",
            "notouts",
            "outs",
            "runs",
            "minutes",
            "high_score",
            "batting_average",
            "balls_faced",
            "batting_strike_rate",
            "hundreds",
            "fifty_plus",
            "ducks",
            "fours",
            "sixes",
            "innings_bowled",
            "balls",
            "maidens",
            "conceded",
            "wickets",
            "bbi",
            "bbm",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "four_plus_wickets",
            "five_wickets",
            "ten_wickets",
            "matches_keeper",
            "matches_fielder",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "max_dismissals",
            "dismissals_per_inns",
            "allround_average",
        ],
        "year": [
            "year",
            "player",
            "matches",
            "innings",
            "notouts",
            "outs",
            "runs",
            "minutes",
            "high_score",
            "batting_average",
            "balls_faced",
            "batting_strike_rate",
            "hundreds",
            "fifty_plus",
            "ducks",
            "fours",
            "sixes",
            "innings_bowled",
            "balls",
            "maidens",
            "conceded",
            "wickets",
            "bbi",
            "bbm",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "four_plus_wickets",
            "five_wickets",
            "ten_wickets",
            "matches_keeper",
            "matches_fielder",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "max_dismissals",
            "dismissals_per_inns",
            "allround_average",
        ],
    },
    "batting": {
        "": [
            "player",
            "start",
            "matches",
            "innings",
            "notouts",
            "outs",
            "runs",
            "minutes",
            "balls_faced",
            "high_score",
            "batting_average",
            "batting_strike_rate",
            "hundreds",
            "fifty_plus",
            "ducks",
            "fours",
            "sixes",
        ],
        "bowler_summary": [
            "dis_bowler",
            "dis_span",
            "dis_matches",
            "dis_dismissals",
            "dis_bowled",
            "dis_caught_fielder",
            "dis_caught_keeper",
            "dis_stumped",
            "dis_lbw",
            "dis_hit_wicket",
            "dis_matches_per_dismissal",
            "dis_average",
            "dis_ducks",
        ],
        "cumulative": ["start", "batting_average", "batting_strike_rate"],
        "dismissal_list": [
            "start",
            "dis_how_out",
            "dis_fielder",
            "dis_bowler",
            "dis_runs",
            "dis_innings_number",
        ],
        "dismissal_summary": [
            "default",
            "start",
            "dis_dismissals",
            "dis_bowled",
            "dis_caught_fielder",
            "dis_caught_keeper",
            "dis_stumped",
            "dis_lbw",
            "dis_hit_wicket",
            "dis_run_out",
            "dis_other",
            "dis_not_out",
            "dis_average",
            "dis_ducks",
        ],
        "fielder_summary": [
            "dis_fielder",
            "dis_span",
            "dis_matches",
            "dis_dismissals",
            "dis_caught_fielder",
            "dis_caught_keeper",
            "dis_stumped",
            "dis_matches_per_dismissal",
            "dis_average",
            "dis_ducks",
        ],
        "fow_list": [
            "partner",
            "start",
            "fow_wicket",
            "fow_score",
            "fow_in",
            "fow_out",
            "fow_innings_number",
        ],
        "fow_summary": [
            "partner",
            "start",
            "fow_innings",
            "fow_notouts",
            "fow_outs",
            "fow_runs",
            "fow_high_score",
            "fow_average",
            "fow_hundreds",
            "fow_fifty_plus",
        ],
        "ground": [
            "player",
            "start",
            "matches",
            "innings",
            "notouts",
            "outs",
            "runs",
            "minutes",
            "balls_faced",
            "high_score",
            "batting_average",
            "batting_strike_rate",
            "hundreds",
            "fifty_plus",
            "ducks",
            "fours",
            "sixes",
        ],
        "host": [
            "player",
            "start",
            "matches",
            "innings",
            "notouts",
            "outs",
            "runs",
            "minutes",
            "balls_faced",
            "high_score",
            "batting_average",
            "batting_strike_rate",
            "hundreds",
            "fifty_plus",
            "ducks",
            "fours",
            "sixes",
        ],
        "innings": [
            "player",
            "start",
            "age",
            "batted_score",
            "minutes",
            "balls_faced",
            "fours",
            "sixes",
            "batting_strike_rate",
            "batting_position",
            "dismissal",
            "innings_number",
        ],
        "match": [
            "player",
            "start",
            "age",
            "batting_score1",
            "batting_score2",
            "runs",
            "minutes",
            "balls_faced",
            "fours",
            "sixes",
            "batting_strike_rate",
            "innings",
            "notouts",
            "outs",
            "high_score",
            "batting_average",
            "hundreds",
            "fifty_plus",
            "ducks",
        ],
        "opposition": [
            "player",
            "start",
            "matches",
            "innings",
            "notouts",
            "outs",
            "runs",
            "minutes",
            "balls_faced",
            "high_score",
            "batting_average",
            "batting_strike_rate",
            "hundreds",
            "fifty_plus",
            "ducks",
            "fours",
            "sixes",
        ],
        "reverse_cumulative": ["start", "batting_average", "batting_strike_rate"],
        "season": [
            "season",
            "player",
            "matches",
            "innings",
            "notouts",
            "outs",
            "runs",
            "minutes",
            "balls_faced",
            "high_score",
            "batting_average",
            "batting_strike_rate",
            "hundreds",
            "fifty_plus",
            "ducks",
            "fours",
            "sixes",
        ],
        "series": [
            "player",
            "start",
            "matches",
            "innings",
            "notouts",
            "outs",
            "runs",
            "minutes",
            "balls_faced",
            "high_score",
            "batting_average",
            "batting_strike_rate",
            "hundreds",
            "fifty_plus",
            "ducks",
            "fours",
            "sixes",
        ],
        "year": [
            "year",
            "player",
            "matches",
            "innings",
            "notouts",
            "outs",
            "runs",
            "minutes",
            "balls_faced",
            "high_score",
            "batting_average",
            "batting_strike_rate",
            "hundreds",
            "fifty_plus",
            "ducks",
            "fours",
            "sixes",
        ],
    },
    "bowling": {
        "": [
            "player",
            "start",
            "matches",
            "innings_bowled",
            "balls",
            "overs",
            "maidens",
            "conceded",
            "wickets",
            "bbi",
            "bbm",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "four_plus_wickets",
            "five_wickets",
            "ten_wickets",
        ],
        "batsman_summary": [
            "dis_batsman",
            "dis_span",
            "dis_matches",
            "dis_dismissals",
            "dis_bowled",
            "dis_caught_fielder",
            "dis_caught_keeper",
            "dis_stumped",
            "dis_lbw",
            "dis_hit_wicket",
            "dis_matches_per_dismissal",
            "dis_average",
            "dis_ducks",
        ],
        "cumulative": ["start", "bowling_average", "economy_rate", "bowling_strike_rate"],
        "dismissal_list": [
            "start",
            "dis_batsman",
            "dis_how_out",
            "dis_fielder",
            "dis_runs",
            "dis_innings_number",
        ],
        "dismissal_summary": [
            "default",
            "dis_span",
            "dis_dismissals",
            "dis_bowled",
            "dis_caught_fielder",
            "dis_caught_keeper",
            "dis_stumped",
            "dis_lbw",
            "dis_hit_wicket",
            "dis_average",
            "dis_ducks",
        ],
        "fielder_summary": [
            "dis_fielder",
            "dis_span",
            "dis_matches",
            "dis_dismissals",
            "dis_caught_fielder",
            "dis_caught_keeper",
            "dis_stumped",
            "dis_matches_per_dismissal",
            "dis_average",
            "dis_ducks",
        ],
        "ground": [
            "player",
            "start",
            "matches",
            "innings_bowled",
            "balls",
            "overs",
            "maidens",
            "conceded",
            "wickets",
            "bbi",
            "bbm",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "four_plus_wickets",
            "five_wickets",
            "ten_wickets",
        ],
        "host": [
            "player",
            "start",
            "matches",
            "innings_bowled",
            "balls",
            "overs",
            "maidens",
            "conceded",
            "wickets",
            "bbi",
            "bbm",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "four_plus_wickets",
            "five_wickets",
            "ten_wickets",
        ],
        "innings": [
            "player",
            "start",
            "age",
            "overs",
            "maidens",
            "conceded",
            "wickets",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "bowling_position",
        ],
        "match": [
            "player",
            "start",
            "age",
            "innings_bowled",
            "overs",
            "maidens",
            "conceded",
            "wickets",
            "bbi",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "four_plus_wickets",
            "five_wickets",
            "ten_wickets",
        ],
        "opposition": [
            "player",
            "start",
            "matches",
            "innings_bowled",
            "balls",
            "overs",
            "maidens",
            "conceded",
            "wickets",
            "bbi",
            "bbm",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "four_plus_wickets",
            "five_wickets",
            "ten_wickets",
        ],
        "reverse_cumulative": ["start", "bowling_average", "economy_rate", "bowling_strike_rate"],
        "season": [
            "season",
            "player",
            "matches",
            "innings_bowled",
            "balls",
            "overs",
            "maidens",
            "conceded",
            "wickets",
            "bbi",
            "bbm",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "four_plus_wickets",
            "five_wickets",
            "ten_wickets",
        ],
        "series": [
            "player",
            "start",
            "matches",
            "innings_bowled",
            "balls",
            "overs",
            "maidens",
            "conceded",
            "wickets",
            "bbi",
            "bbm",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "four_plus_wickets",
            "five_wickets",
            "ten_wickets",
        ],
        "year": [
            "year",
            "player",
            "matches",
            "innings_bowled",
            "balls",
            "overs",
            "maidens",
            "conceded",
            "wickets",
            "bbi",
            "bbm",
            "bowling_average",
            "economy_rate",
            "bowling_strike_rate",
            "four_plus_wickets",
            "five_wickets",
            "ten_wickets",
        ],
    },
    "fielding": {
        "": [
            "player",
            "start",
            "age",
            "matches",
            "matches_keeper",
            "matches_fielder",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "max_dismissals",
            "dismissals_per_inns",
        ],
        "batsman_summary": [
            "dis_batsman",
            "dis_span",
            "dis_matches",
            "dis_dismissals",
            "dis_caught_fielder",
            "dis_caught_keeper",
            "dis_stumped",
            "dis_matches_per_dismissal",
            "dis_average",
            "dis_ducks",
        ],
        "bowler_summary": [
            "dis_bowler",
            "dis_span",
            "dis_matches",
            "dis_dismissals",
            "dis_caught_fielder",
            "dis_caught_keeper",
            "dis_stumped",
            "dis_matches_per_dismissal",
            "dis_average",
            "dis_ducks",
        ],
        "cumulative": ["start", "dismissals_per_inns"],
        "dismissal_list": [
            "start",
            "dis_batsman",
            "dis_how_out",
            "dis_bowler",
            "dis_runs",
            "dis_innings_number",
        ],
        "dismissal_summary": [
            "default",
            "dis_span",
            "dis_dismissals",
            "dis_caught_fielder",
            "dis_caught_keeper",
            "dis_stumped",
            "dis_average",
            "dis_ducks",
        ],
        "ground": [
            "player",
            "start",
            "age",
            "matches",
            "matches_keeper",
            "matches_fielder",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "max_dismissals",
            "dismissals_per_inns",
        ],
        "host": [
            "player",
            "start",
            "age",
            "matches",
            "matches_keeper",
            "matches_fielder",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "max_dismissals",
            "dismissals_per_inns",
        ],
        "innings": [
            "player",
            "start",
            "age",
            "fielded_dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
        ],
        "match": [
            "player",
            "start",
            "age",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "dismissals_per_inns",
        ],
        "opposition": [
            "player",
            "start",
            "age",
            "matches",
            "matches_keeper",
            "matches_fielder",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "max_dismissals",
            "dismissals_per_inns",
        ],
        "reverse_cumulative": ["start", "dismissals_per_inns"],
        "season": [
            "season",
            "player",
            "age",
            "matches",
            "matches_keeper",
            "matches_fielder",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "max_dismissals",
            "dismissals_per_inns",
        ],
        "series": [
            "player",
            "start",
            "age",
            "matches",
            "matches_keeper",
            "matches_fielder",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "max_dismissals",
            "dismissals_per_inns",
        ],
        "year": [
            "year",
            "player",
            "age",
            "matches",
            "matches_keeper",
            "matches_fielder",
            "innings_fielded",
            "dismissals",
            "caught",
            "stumped",
            "caught_keeper",
            "caught_fielder",
            "max_dismissals",
            "dismissals_per_inns",
        ],
    },
    "fow": {
        "": [
            "partners",
            "start",
            "fow_innings",
            "fow_notouts",
            "fow_outs",
            "fow_runs",
            "fow_high_score",
            "fow_average",
            "fow_balls_faced",
            "fow_run_rate",
            "fow_hundreds",
            "fow_fifty_plus",
        ],
        "ground": [
            "partners",
            "start",
            "fow_innings",
            "fow_notouts",
            "fow_outs",
            "fow_runs",
            "fow_high_score",
            "fow_average",
            "fow_balls_faced",
            "fow_run_rate",
            "fow_hundreds",
            "fow_fifty_plus",
        ],
        "host": [
            "partners",
            "start",
            "fow_innings",
            "fow_notouts",
            "fow_outs",
            "fow_runs",
            "fow_high_score",
            "fow_average",
            "fow_balls_faced",
            "fow_run_rate",
            "fow_hundreds",
            "fow_fifty_plus",
        ],
        "innings": [
            "partners",
            "start",
            "fow_wicket",
            "fow_score",
            "fow_balls_faced",
            "fow_run_rate",
            "fow_in",
            "fow_out",
            "fow_innings_number",
        ],
        "match": [
            "partners",
            "start",
            "fow_innings",
            "fow_notouts",
            "fow_outs",
            "fow_runs",
            "fow_high_score",
            "fow_average",
            "fow_balls_faced",
            "fow_run_rate",
            "fow_hundreds",
            "fow_fifty_plus",
        ],
        "opposition": [
            "partners",
            "start",
            "fow_innings",
            "fow_notouts",
            "fow_outs",
            "fow_runs",
            "fow_high_score",
            "fow_average",
            "fow_balls_faced",
            "fow_run_rate",
            "fow_hundreds",
            "fow_fifty_plus",
        ],
        "season": [
            "season",
            "partners",
            "fow_innings",
            "fow_notouts",
            "fow_outs",
            "fow_runs",
            "fow_high_score",
            "fow_average",
            "fow_balls_faced",
            "fow_run_rate",
            "fow_hundreds",
            "fow_fifty_plus",
        ],
        "series": [
            "partners",
            "start",
            "fow_innings",
            "fow_notouts",
            "fow_outs",
            "fow_runs",
            "fow_high_score",
            "fow_average",
            "fow_balls_faced",
            "fow_run_rate",
            "fow_hundreds",
            "fow_fifty_plus",
        ],
        "year": [
            "year",
            "partners",
            "fow_innings",
            "fow_notouts",
            "fow_outs",
            "fow_runs",
            "fow_high_score",
            "fow_average",
            "fow_balls_faced",
            "fow_run_rate",
            "fow_hundreds",
            "fow_fifty_plus",
        ],
    },
    "team": {
        "": [
            "team",
            "start",
            "matches",
            "won",
            "lost",
            "tied",
            "drawn",
            "no_result",
            "win_loss_ratio",
            "percentage_won",
            "percentage_lost",
            "percentage_drawn",
            "percentage_tied",
            "percentage_no_result",
            "runs",
            "wickets",
            "balls",
            "team_average",
            "runs_per_over",
            "team_innings",
            "team_high_score",
            "team_low_score",
        ],
        "cumulative": [
            "start",
            "win_loss_ratio",
            "percentage_won",
            "percentage_lost",
            "percentage_drawn",
            "percentage_tied",
            "percentage_no_result",
            "team_average",
            "runs_per_over",
        ],
        "extras": [
            "team",
            "start",
            "matches",
            "extras",
            "byes",
            "legbyes",
            "wides",
            "noballs",
            "penalties",
            "runs",
            "percent_extras",
            "wickets",
            "balls",
        ],
        "extras_innings": [
            "team",
            "start",
            "extras",
            "byes",
            "legbyes",
            "wides",
            "noballs",
            "penalties",
            "team_score",
            "percent_extras",
            "team_wickets",
            "team_overs",
            "innings_number",
        ],
        "ground": [
            "team",
            "start",
            "matches",
            "won",
            "lost",
            "tied",
            "drawn",
            "no_result",
            "win_loss_ratio",
            "percentage_won",
            "percentage_lost",
            "percentage_drawn",
            "percentage_tied",
            "percentage_no_result",
            "runs",
            "wickets",
            "balls",
            "team_average",
            "runs_per_over",
            "team_innings",
            "team_high_score",
            "team_low_score",
        ],
        "ground_results": [
            "start",
            "winner",
            "result",
            "amount",
            "amount_balls",
            "toss",
            "batting_fielding_first",
        ],
        "host": [
            "team",
            "start",
            "matches",
            "won",
            "lost",
            "tied",
            "drawn",
            "no_result",
            "win_loss_ratio",
            "percentage_won",
            "percentage_lost",
            "percentage_drawn",
            "percentage_tied",
            "percentage_no_result",
            "runs",
            "wickets",
            "balls",
            "team_average",
            "runs_per_over",
            "team_innings",
            "team_high_score",
            "team_low_score",
        ],
        "innings": [
            "team",
            "start",
            "team_score",
            "team_wickets",
            "team_overs",
            "target",
            "lead",
            "team_average",
            "runs_per_over",
            "innings_number",
            "result",
        ],
        "match": [
            "team",
            "start",
            "runs",
            "wickets",
            "balls",
            "team_average",
            "runs_per_over",
            "result",
        ],
        "opposition": [
            "team",
            "start",
            "matches",
            "won",
            "lost",
            "tied",
            "drawn",
            "no_result",
            "win_loss_ratio",
            "percentage_won",
            "percentage_lost",
            "percentage_drawn",
            "percentage_tied",
            "percentage_no_result",
            "runs",
            "wickets",
            "balls",
            "team_average",
            "runs_per_over",
            "team_innings",
            "team_high_score",
            "team_low_score",
        ],
        "results": [
            "team",
            "start",
            "result",
            "amount",
            "amount_balls",
            "toss",
            "batting_fielding_first",
        ],
        "reverse_cumulative": [
            "start",
            "win_loss_ratio",
            "percentage_won",
            "percentage_lost",
            "percentage_drawn",
            "percentage_tied",
            "percentage_no_result",
            "team_average",
            "runs_per_over",
        ],
        "season": [
            "season",
            "team",
            "matches",
            "won",
            "lost",
            "tied",
            "drawn",
            "no_result",
            "win_loss_ratio",
            "percentage_won",
            "percentage_lost",
            "percentage_drawn",
            "percentage_tied",
            "percentage_no_result",
            "runs",
            "wickets",
            "balls",
            "team_average",
            "runs_per_over",
            "team_innings",
            "team_high_score",
            "team_low_score",
        ],
        "series": [
            "team",
            "start",
            "matches",
            "won",
            "lost",
            "tied",
            "drawn",
            "no_result",
            "win_loss_ratio",
            "percentage_won",
            "percentage_lost",
            "percentage_drawn",
            "percentage_tied",
            "percentage_no_result",
            "runs",
            "wickets",
            "balls",
            "team_average",
            "runs_per_over",
            "team_innings",
            "team_high_score",
            "team_low_score",
        ],
        "toss_results": ["start", "toss_winner", "toss_decision", "winner", "result"],
        "year": [
            "year",
            "team",
            "matches",
            "won",
            "lost",
            "tied",
            "drawn",
            "no_result",
            "win_loss_ratio",
            "percentage_won",
            "percentage_lost",
            "percentage_drawn",
            "percentage_tied",
            "percentage_no_result",
            "runs",
            "wickets",
            "balls",
            "team_average",
            "runs_per_over",
            "team_innings",
            "team_high_score",
            "team_low_score",
        ],
    },
}

RANGE_VAL_FIELDS = {
    "aggregate": {},
    "allround": {
        "age": "age",
        "balls": "balls",
        "batting_position": "batting_position",
        "bowling_position": "bowling_position",
        "caught": "caught",
        "conceded": "conceded",
        "runs": "runs",
        "stumped": "stumped",
        "wickets": "wickets",
    },
    "batting": {"age": "age", "batting_position": "batting_position", "runs": "runs"},
    "bowling": {
        "age": "age",
        "balls": "balls",
        "bowling_position": "bowling_position",
        "conceded": "conceded",
        "wickets": "wickets",
    },
    "fielding": {"age": "age", "caught": "caught", "stumped": "stumped"},
    "fow": {"partnership_runs": "partnership_runs", "partnership_wicket": "partnership_wicket"},
    "team": {"balls": "balls", "runs": "runs", "wickets": "wickets"},
}

CHOICE_VALUES = {
    "batting_fielding_first": ["1", "2"],
    "batting_hand": ["1", "2"],
    "bowling_hand": ["1", "2", "3"],
    "bowling_pacespin": ["1", "2", "3"],
    "captain": ["0", "1"],
    "debut_or_last": ["1", "2", "3", "4"],
    "dismissal": ["1", "11", "12", "13", "2", "3", "4", "5", "6", "7", "8"],
    "event": ["1", "2", "3", "4"],
    "final_type": ["0", "1"],
    "floodlit": ["1", "2"],
    "fow_type": ["1", "2", "3"],
    "home_or_away": ["1", "2", "3"],
    "innings_number": ["1", "2", "3", "4"],
    "keeper": ["0", "1"],
    "outs": ["0", "1"],
    "result": ["1", "2", "3", "4"],
    "team_view": ["bowl"],
    "toss": ["1", "2"],
    "tournament_type": ["2", "3", "5"],
}

QUICKPICK_FIELDS = [
    "agequickpick",
    "ballsquickpick",
    "batting_positionquickpick",
    "bowling_positionquickpick",
    "caughtquickpick",
    "concededquickpick",
    "partnership_runsquickpick",
    "partnership_wicketquickpick",
    "qualquickpick",
    "runsquickpick",
    "spanquickpick",
    "stumpedquickpick",
    "wicketsquickpick",
]

PLAYER_PAGE_VIEWS = {
    "allround": [
        "",
        "innings",
        "match",
        "cumulative",
        "reverse_cumulative",
        "series",
        "ground",
        "results",
        "awards_match",
        "awards_series",
    ],
    "batting": [
        "",
        "innings",
        "match",
        "cumulative",
        "reverse_cumulative",
        "series",
        "ground",
        "results",
        "awards_match",
        "awards_series",
        "fow_summary",
        "fow_list",
        "dismissal_summary",
        "bowler_summary",
        "fielder_summary",
        "dismissal_list",
    ],
    "bowling": [
        "",
        "innings",
        "match",
        "cumulative",
        "reverse_cumulative",
        "series",
        "ground",
        "results",
        "awards_match",
        "awards_series",
        "dismissal_summary",
        "batsman_summary",
        "fielder_summary",
        "dismissal_list",
    ],
    "fielding": [
        "",
        "innings",
        "match",
        "cumulative",
        "reverse_cumulative",
        "series",
        "ground",
        "results",
        "awards_match",
        "awards_series",
        "dismissal_summary",
        "batsman_summary",
        "bowler_summary",
        "dismissal_list",
    ],
}
